### ISSUE TITLE
Pressing "Enter" in the `prDetailsModal` anywhere within a textarea full of a PR template puts the cursor at the very end of the input instead

### ISSUE THREAD

**Issue by ndom91** [gitbutlerapp/gitbutler#5741] opened 2024-12-04 15:28 UTC
### Version

0.14.1

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

Say you open the PR Details Modal and it's full of a long PR Template body already. If you click anywhere within the textarea to beign writing in your template, as soon as you press "enter", instead of creating a newline, it'll bump your cursor all the way to the last possibl position. Super annoying :sweat_smile: 

This has been reported by someone in [Discord](https://discord.com/channels/1060193121130000425/1073202153163857920/1313636807748882593) as well.

**Comment by Byron** [comment] 2024-12-05 05:59
This is a probably a duplicate of

* #5645

**Closed** 2024-12-10 10:38 UTC
Labels: bug
