### ISSUE TITLE
Can't open , after closing the app - Ubuntu (gnome)

### ISSUE THREAD

**Issue by oussamaeljabbari** [gitbutlerapp/gitbutler#2630] opened 2024-02-13 17:51 UTC
Can't open the app after closing, until I close it from the tray icon and open it again

Ubuntu:  22.04.3
Gnome: 42.9
WM: Wayland

[Screencast from 02-13-2024 05:13:23 PM.webm](https://github.com/gitbutlerapp/gitbutler/assets/72318899/929f278c-78fc-4a67-b755-9f2322744d73)

**Comment by Legrems** [comment] 2024-02-13 18:21
I have the same problem under arch 6.7.4, i3 4.23, X11 21.1.11.

When clicking on the tray-icon and on `Show gitbutler`, if i have GB open, it closes. If it wasn't open, nothing happen

**Comment by shrutsureja** [comment] 2024-02-14 18:27
I am also facing the same issue in ubuntu 22.04, gnome default.

Once i one the app for the 1st time it works fine but as soon as i close, then it wont open the 2nd time.

**Comment by namanlp** [comment] 2024-02-14 21:37
Actually, as it turns out, GitButler is running in background, and user should be able to open it from system tray. The issue is:

1. There is no system tray icons at all in Gnome.
2. It is not launching from tray icon in other DE as well. But we can simply close it and open a new instance, if there is a Tray Icon

How it should be fixed:
1. System Tray Icon should be fixed.
2. If a user launches the Gitbutler again, while it is in hidden state, it should come to the visible state again.

( 2nd point seems tough to implement I guess )

**Comment by hazrpg** [comment] 2024-02-15 15:38
I had the same issue but it was because a bug happened first #2725 - speaking about it in Discord, I was pointed here and turns out I hadn't realised there was a tray icon due to it being practically hidden on dark mode in Ubuntu 22.04.3.

With dark mode this is what the icon looks like (hint: its between the emoji gnome-shell extension and jetbrains toolbox):
![image](https://github.com/gitbutlerapp/gitbutler/assets/115112/087c4419-6ac4-4ef8-bb83-4697a16ef668)

Hover over it shows it a little bit better:
![image](https://github.com/gitbutlerapp/gitbutler/assets/115112/0eebcfda-e22d-4325-a9ea-bea3ba90198f)

I think the icon should either be designed to work in both light/dark themes (note: I'm using the default Ubuntu dark theme) or have alternate versions displayed depending on the detected theme.

I know gnome has a command-line way of detected the user's preference which is:
```
gsettings get org.gnome.desktop.interface color-scheme
```

Which will output either:

1. default
2. prefer-dark
3. prefer-light

e.g.
![image](https://github.com/gitbutlerapp/gitbutler/assets/115112/5295c378-fa2a-479e-8e33-2e3427e93825)

So it might be worth utilising that (if gsettings exists) to poke it. There might also be a way to get the setting somehow elsewhere in `.local` possibly or `.config` - but I'm unsure about that.

**Comment by KroniK907** [comment] 2024-02-15 21:36
I think the best solution to this issue would be to provide a system wide option for the "Close to tray" function. 

When enabled, closing the window would keep the process running in the background and allow the window to be re-opened via the tray icon.

When disabled, closing the window would also kill the background process.

**Comment by KroniK907** [comment] 2024-02-15 21:55
Looking into the code, it appears that this behavior originates here:

https://github.com/gitbutlerapp/gitbutler/blob/f084b6bcf79266b075877dda3f0943f3c4d54c85/gitbutler-app/src/bin.rs#L63

**Comment by namanlp** [comment] 2024-02-19 08:20
I found a fix for this issue 🎉 

I will create a PR after code cleanup.

**Comment by pravinkori** [comment] 2024-02-19 14:35
This bug is persistent across all Ubuntu machines. 
[Screencast from 19-02-24 07:56:30 PM IST.webm](https://github.com/gitbutlerapp/gitbutler/assets/58039953/53542f44-1b2c-4f7d-a586-245f66ca1216)

**Comment by mnecas** [comment] 2024-02-21 10:21
The issue still happens even after upgrading to ./git-butler_0.10.13_amd64.AppImage

**Comment by KroniK907** [comment] 2024-02-21 19:06
I can also confirm that the AppImage on both Ubuntu and Fedora still have the issue of the process not being killed when the window is closed. 
![WindowsTerminal_2024-02-14_08-32-51](https://github.com/gitbutlerapp/gitbutler/assets/4690564/f44678e1-9327-4a64-807e-e256b97d531f)

**Comment by LopesLs** [comment] 2024-02-21 22:33
I'm facing the same issue, my os is `Linux Mint 21.3 x86_64 MATE`.

When i close the app it stay runs in the background like as a trail-icon waiting for be activated, but i don't have trail-icons showing, click in the gitbutler icon for open again not works.

The solution for me now is close all process about gitbutler and re-run the app.

https://github.com/gitbutlerapp/gitbutler/assets/97265556/d45e59b4-bdda-4947-87d9-6d317317d422

**Closed** 2024-02-21 22:50 UTC
Labels: bug

**Comment by mnecas** [comment] 2024-02-26 08:05
Yup the https://github.com/gitbutlerapp/gitbutler/pull/2861 did it, thank you!
