### ISSUE TITLE
Feature Request: Ability to Stack Changes

### ISSUE THREAD

**Issue by eabrouwer3** [gitbutlerapp/gitbutler#3031] opened 2024-03-05 00:10 UTC
A lot of times, I find myself wanting to push incremental PRs for a feature, so my coworkers aren't hit with a huge PR at the end. Usually I'll work on a branch, then I'll branch off of that and do the next piece of work, and so on, creating a few PRs for the feature to be merged in succession. I thought I'd be able to do that with gitbutler, but it's not letting me move new changes to files I've already committed to, to a new virtual branch. Is it actually possible and I'm just doing something wrong? Or is this not something that I can do with gitbutler right now.

Thanks for the great product! I've been using it all day after learning about it!

**Comment by mltsy** [comment] 2024-03-08 21:27
This is interesting - I actually *am* able to do what you're describing.  Can you list the steps you're attempting, and where/how it fails?

**Comment by joshkim81** [comment] 2024-03-14 18:38
Not sure if I'm experiencing the same issue but I'm also having trouble adding individual changes to a virtual branch. If there are multiple changes from a single file to drag and drop in my workspace, some of them move over to a virtual branch and others don't move at all no matter how many times I try. I'm not doing the same workflow of branching off other branches so that doesn't seem to be a repro step.

**Comment by eabrouwer3** [comment] 2024-03-22 16:22
I put some changes on a virtual branch, then when I make some more changes, I can't move those files to a new virtual branch if they're in the same file. The files have a little "lock" icon on them and they don't drop where I want them to, on a new branch. They just go back to the initial branch.

**Comment by mltsy** [comment] 2024-03-22 20:16
Could be related to https://github.com/gitbutlerapp/gitbutler/issues/3258 perhaps?

**Comment by hannesweisbach** [comment] 2024-04-11 11:08
I use a similar (or the same?) approach as the TO and experience the same issue.

If I hover over the lock icon it says "Locked due to conflicts in <Previous commit message> <commit SHA>". If I open the hunk it is tagged "Locked". If I hover over the tag the tooltip reads "File changes cannot be moved because part of this file was already committed into this branch".

I interpret that as parts of a file can not be committed to multiple virtual branches. Is my interpretation correct?

**Comment by aaronzhongg** [comment] 2024-04-26 05:36
I have the same use case as @eabrouwer3.

Just to clarify this with an image, I have some commits in my local vbranch (that have also been pushed, but that should be irrelevant), and some changes that I want to include in another remote branch. (So I can create a series of dependent PRs)

Intuitively I want to drag and drop all of these changes to create a new vbranch but it prevents me because the changes are dependent on an earlier commit in the current branch.

![Screenshot 2024-04-26 at 5 28 43 PM](https://github.com/gitbutlerapp/gitbutler/assets/14045995/88550701-2319-4ca1-904e-000ed7dd8cb2)

**Comment by chip-davis** [comment] 2024-04-29 15:33
Same experience here, really wish this could work like that!

**Comment by robin-lcr** [comment] 2024-05-17 07:38
Hello,

I have the exact same issue, I would like to do incremental PR by having my virtual branches to rely on each other, so I can move the changes onto another one, even if it depends on previous changes.
Like creating a virtual branches based on another one.

I would really like this feature, as it is a bit of a blocker for me to "completely" switch to Git Butler.

**Comment by markalanevans** [comment] 2024-07-18 16:23
I'm in the dscord now asking a very similar question.

I want to use a flow like these mentioned here:
https://github.com/gitext-rs/git-stack/blob/main/docs/comparison.md

**Comment by markalanevans** [comment] 2024-07-18 21:48
FYI I got an update via Discourse. 

The GitButler team is aware of the need but at the moment GitButler doesn't fully support the stacking & syncing of branches.

**Comment by krlvi** [comment] 2024-08-16 12:37
I am currently working on this. Should have an update soon

**Comment by krlvi** [comment] 2024-09-03 07:29
Update: got the thing working, now in the process of creating UI/UX for it in the application

**Comment by krlvi** [comment] 2024-09-03 11:30
Question for anybody interested in stacking - when you do stack, do you expect (or wish to) have other developers contributing with new commits to the stack PRs? @eabrouwer3 @markalanevans @aaronzhongg @robin-lcr @chip-davis @hannesweisbach @mltsy 

Thank you for your time in helping out realizing the UX of this! 🙏

**Comment by abey79** [comment] 2024-09-03 12:10
In my case, I'd say, generally, no. The whole idea of stacking PR is to make them more digestible for the reviewer(s), which somewhat contradicts the idea of that stack being a good place to collaborate in the first place.

**Comment by chip-davis** [comment] 2024-09-03 12:29
I'm in the same boat as @abey79 !

**Comment by aaronzhongg** [comment] 2024-09-04 04:32
an unlikely scenario - but not impossible. fwiw, none of my co-workers are using gitbutler

**Comment by robin-lcr** [comment] 2024-09-04 06:58
I also agree with @abey79, although I'm not sure I'm representative of the most because I work in a small team and we don't need to collaborate on the same features, I'd say I don't expect this to happen.

Also, thank you for implementing this ! :)

**Comment by benjixx** [comment] 2024-09-08 20:20
In my opinion this feature together with #2513 (moving line-based changes around between commits) would be the killer feature. Would be happy to see this. Thanks for the great work!

**Comment by hannesweisbach** [comment] 2024-09-18 09:08
I thought about this for a while and just to make sure I understand that right: The question is whether or not it is a use-case where I have a bunch of (open) PRs and stack them locally. Then a collaborator makes a commit to one of the open PRs which I eventually pull and then stacked PR has to be updated?

If so, I agree with @abey79. I don't foresee being in that situation. However someone else might be.

Additionally, none of my coworkers are using gitbutler at this moment either.

**Comment by filip-coherence** [comment] 2024-11-20 12:57
What's the status of this? I have to say, I love gitbutler, but in my current project this is the main workflow (stacking branches and PRs to be merged in succession) and so it renders gitbutler unusable.

**Comment by Byron** [comment] 2024-11-20 17:59
Probably best in a [nightly release](https://app.gitbutler.com/downloads), it is possible to turn the feature on in the application settings.

<img width="1051" alt="Screenshot 2024-11-20 at 18 57 08" src="https://github.com/user-attachments/assets/e5ab7817-10ef-4da7-a4b7-61c4e91a50aa">

I recommend to be particularly mindful when using it as that would facilitate submitting reproducible bug reports in case you come across unwanted behaviour.

**Comment by krlvi** [comment] 2024-11-26 17:37
> What's the status of this? I have to say, I love gitbutler, but in my current project this is the main workflow (stacking branches and PRs to be merged in succession) and so it renders gitbutler unusable.

It took us a while, but it's finally out! Check out the latest release https://github.com/gitbutlerapp/gitbutler/releases/tag/release%2F0.14.0 and also be sure to take a look at the docs here 
https://docs.gitbutler.com/features/stacked-branches 

I would love to hear what you guys think!

**Comment by krlvi** [comment] 2024-11-27 14:37
I am closing this one as completed. Please, if you find any issues, or if you have suggestions for improving this functionality - create a new GitHub issue or reach out on Discord https://discord.com/invite/MmFkmaJ42D

**Closed by krlvi** 2024-11-27 14:37 UTC
Labels: new feature, planned
