### ISSUE TITLE
Feature: Stacked vbranches

### ISSUE THREAD

**Issue by Caleb-T-Owens** [gitbutlerapp/gitbutler#3104] opened 2024-03-11 00:50 UTC
Just opening this to track the potential feature of stacked vbranches

From Kiril: What i'd like for the tool to do is to have the ability to express lanes/vbranches that are dependent on other lanes (stacked). But there's still some work to get it there

**Comment by mtsgrd** [comment] 2024-03-13 10:41
Closing as duplicate of #3031.

**Comment by krlvi** [comment] 2024-08-18 10:02
i think this is indeed a dupe of https://github.com/gitbutlerapp/gitbutler/issues/3031, gonna close it

**Closed by krlvi** 2024-08-18 10:02 UTC
Labels: new feature
