### ISSUE TITLE
Hunks not in order

### ISSUE THREAD

**Issue by schacon** [gitbutlerapp/gitbutler#3451] opened 2024-04-08 02:23 UTC
Since about release 10.28 I believe, we've started getting in some circumstances, a "Hunk not in order or overlap" issue that prevents people from committing and looks something like this:
```
2024-03-27T16:06:54.482959Z ERROR commit_virtual_branch: gitbutler-app/src/virtual_branches/errors.rs:496: commit error error=error parsing patch: Hunks not in order or overlap project_id=[PROJECT_ID] branch=[BRANCH_ID] commit message ownership=Some(BranchOwnershipClaims { claims: [OwnershipClaim { file_path: "src/example.ts", hunks: [Hunk { hash: None, timestamp_ms: None, start: 104, end: 105 }] }] }) run_hooks=false
```

Also seen in Discord: 

* https://discord.com/channels/1060193121130000425/1223970695042568224/1223972691967475875
* https://discord.com/channels/1060193121130000425/1220833850650001428/1223399606675701811
* https://discord.com/channels/1060193121130000425/1073202153163857920/1222582292447363193

Certainly, this should be recoverable and not prevent further usage.

**Comment by Byron** [comment] 2024-04-08 09:19
Here I my attempts to reproduce the issue, with a local dev build at e7377132bf902b6ee3637cf367aea36a86897915.

I tried to reproduce with [this comment](https://discord.com/channels/1060193121130000425/1223970695042568224/1224840846613151846) from the  [first discord thread](https://discord.com/channels/1060193121130000425/1223970695042568224/1223972691967475875) listed above, but it detects the conflict and refuses to apply the branch. However, the conflict-resolution people talk about also doesn't show up. The UI shows an error in the console though.

```
code: "errors.branches"
message: "Branch f8be11a5-6f21-4302-8f46-c1ca9dab53b5 is in a conflicing state"
```

Interestingly, I also wasn't able to find the error message strings anywhere, and I trued substrings of these in this repo, in `git2-rs` and in `libgit2` (even though a version of `libgit2` is included in the repository of `git2-rs`).

I also noticed that errors aren't actually traced into the log anymore, and I will bring up a PR with a fix later today.

**Comment by mtsgrd** [comment] 2024-04-08 09:26
I had a look at that comment, and I'm wondering if we have one or two problems? I wasn't expecting "Hunks not in order or overlap" to only show when you try and make a commit, not when applying a conflicting branch.

**Comment by schacon** [comment] 2024-04-08 09:40
It's coming from diffy: https://github.com/bmwill/diffy/blob/824674ee823e82f45f5498c113f4934233b8910e/src/patch/parse.rs#L213

So this is probably when we're trying to apply the patch to create the tree for the virtual branch: https://github.com/gitbutlerapp/gitbutler/blob/d2dde6cec539b4562877b78a00e9deacb18cf4e4/crates/gitbutler-core/src/virtual_branches/virtual.rs#L2531

So whatever we're trying to create a patch out of is now getting broken somehow (where this wasn't an issue before 10.27).

**Comment by schacon** [comment] 2024-04-10 07:58
I think tcvs in Discord got us much more interestingly farther here: https://discord.com/channels/1060193121130000425/1206670506271707156/1227459984598630491

He found that in this part: https://github.com/gitbutlerapp/gitbutler/blob/87cfadffaf1cf555608095210fe57adf9877cb6b/crates/gitbutler-core/src/virtual_branches/virtual.rs#L2530

The `all_diffs` contains duplicate diffs, which makes sense why you can't apply them all.

One solution which would work would be to deduplicate the `all_diffs` array, but that seems like it's patching the wrong problem. We should probably figure out why we're getting duplicate diffs in that array in the first place.

**Comment by roderik** [comment] 2024-04-14 12:38
I'm experiencing the same thing right now:

```
2024-04-14T12:35:25.541341Z ERROR commit_virtual_branch: crates/gitbutler-tauri/src/virtual_branches.rs:22: error=Error(error parsing patch: Hunks not in order or overlap) [3mproject_id[0m[2m=[0mb62e0f66-0449-453b-8316-8a2d260176ca [3mbranch[0m[2m=[0mff86dea7-3872-41a7-a485-0145b0bdf0bc feat: track additional nodejs metrics [3mownership[0m[2m=[0mSome(BranchOwnershipClaims { claims: [OwnershipClaim { file_path: "charts/settlemint/charts/observability/values.yaml", hunks: [Hunk { hash: Some("c0e731ca5815d2dd32e36be9223aea9a"), timestamp_ms: None, start: 326, end: 333 }] }] }) [3mrun_hooks[0m[2m=[0mfalse
2024-04-14T12:35:25.541355Z  INFO commit_virtual_branch: crates/gitbutler-tauri/src/virtual_branches.rs:22: close time.busy=179ms time.idle=34.6µs [3mproject_id[0m[2m=[0mb62e0f66-0449-453b-8316-8a2d260176ca [3mbranch[0m[2m=[0mff86dea7-3872-41a7-a485-0145b0bdf0bc feat: track additional nodejs metrics [3mownership[0m[2m=[0mSome(BranchOwnershipClaims { claims: [OwnershipClaim { file_path: "charts/settlemint/charts/observability/values.yaml", hunks: [Hunk { hash: Some("c0e731ca5815d2dd32e36be9223aea9a"), timestamp_ms: None, start: 326, end: 333 }] }] }) [3mrun_hooks[0m[2m=[0mfalse
```

For a not too complex change 
![CleanShot 2024-04-14 at 14 36 53@2x](https://github.com/gitbutlerapp/gitbutler/assets/16780/afdc0ea1-c94a-4f28-861e-0ef7319fd081)

changing the following in a yaml file

```
        {{- if .Values.endpoints.internal.prometheus.enabled }}
        prometheus.remote_write "btp_metrics" {
            endpoint {
                url = {{ .Values.endpoints.internal.prometheus.url | quote }}

                write_relabel_config {
                    source_labels = ["__name__"]
                    regex         = "besu_blockchain_chain_head_gas_limit|besu_blockchain_chain_head_gas_used|besu_blockchain_chain_head_timestamp|besu_blockchain_chain_head_transaction_count|besu_transaction_pool_transactions|chain_head_block|consensus_etcdraft_active_nodes|consensus_etcdraft_cluster_size|consensus_etcdraft_committed_block_number|consensus_etcdraft_is_leader|consensus_etcdraft_normal_proposals_received|deployment_count|deployment_head|edge_consensus_block_interval|edge_consensus_block_interval|edge_consensus_num_txs|edge_consensus_rounds|edge_network_peers|edge_txpool_pending_transactions|endorser_proposals_received|endorser_successful_proposals|eth_exe_block_head_block_size_bytes|eth_exe_block_head_gas_limit|eth_exe_block_head_gas_used|eth_exe_block_head_transactions_in_block|eth_exe_block_most_recent_number|eth_exe_chain_id|eth_exe_gas_price_gwei|eth_exe_txpool_transactions|ethereum_best_known_block_number|ethereum_blockchain_height|ethereum_chain_head_number|ethereum_peer_count|ledger_blockchain_height|ledger_transaction_count|nginx_ingress_controller_requests|p2p_peers|participation_consensus_relation|participation_status|proxyd_backend_avg_latency|proxyd_backend_latest_block|proxyd_consensus_backend_in_sync|proxyd_consensus_backend_in_sync|proxyd_rpc_backend_http_response_codes_total|proxyd_rpc_errors_total|proxyd_rpc_requests_total|txpool_pending|txpool_valid|kube_pod_status_ready|kube_pod_labels|nginx_ingress_controller_requests|container_cpu_usage_seconds_total|kube_pod_container_resource_limits|container_memory_working_set_bytes|kubelet_volume_stats_capacity_bytes|kubelet_volume_stats_available_bytes|btp_[a-zA-Z_]+"
                    action        = "keep"
                }
            }
        }
        {{- end }}
```
to (added a few metrics at the beginning of the regex
```
        {{- if .Values.endpoints.internal.prometheus.enabled }}
        prometheus.remote_write "btp_metrics" {
            endpoint {
                url = {{ .Values.endpoints.internal.prometheus.url | quote }}

                write_relabel_config {
                    source_labels = ["__name__"]
                    regex         = "process_cpu_user_seconds_total|process_cpu_system_seconds_total|nodejs_eventloop_lag_seconds|nodejs_version_info|nodejs_heap_space_size_available_bytes|nodejs_heap_space_size_used_bytes|nodejs_heap_space_size_total_bytes|nodejs_active_requests_total|nodejs_active_handles_total|nodejs_external_memory_bytes|nodejs_heap_size_used_bytes|nodejs_heap_size_total_bytes|process_resident_memory_bytes|process_start_time_seconds|besu_blockchain_chain_head_gas_limit|besu_blockchain_chain_head_gas_used|besu_blockchain_chain_head_timestamp|besu_blockchain_chain_head_transaction_count|besu_transaction_pool_transactions|chain_head_block|consensus_etcdraft_active_nodes|consensus_etcdraft_cluster_size|consensus_etcdraft_committed_block_number|consensus_etcdraft_is_leader|consensus_etcdraft_normal_proposals_received|deployment_count|deployment_head|edge_consensus_block_interval|edge_consensus_block_interval|edge_consensus_num_txs|edge_consensus_rounds|edge_network_peers|edge_txpool_pending_transactions|endorser_proposals_received|endorser_successful_proposals|eth_exe_block_head_block_size_bytes|eth_exe_block_head_gas_limit|eth_exe_block_head_gas_used|eth_exe_block_head_transactions_in_block|eth_exe_block_most_recent_number|eth_exe_chain_id|eth_exe_gas_price_gwei|eth_exe_txpool_transactions|ethereum_best_known_block_number|ethereum_blockchain_height|ethereum_chain_head_number|ethereum_peer_count|ledger_blockchain_height|ledger_transaction_count|nginx_ingress_controller_requests|p2p_peers|participation_consensus_relation|participation_status|proxyd_backend_avg_latency|proxyd_backend_latest_block|proxyd_consensus_backend_in_sync|proxyd_consensus_backend_in_sync|proxyd_rpc_backend_http_response_codes_total|proxyd_rpc_errors_total|proxyd_rpc_requests_total|txpool_pending|txpool_valid|kube_pod_status_ready|kube_pod_labels|nginx_ingress_controller_requests|container_cpu_usage_seconds_total|kube_pod_container_resource_limits|container_memory_working_set_bytes|kubelet_volume_stats_capacity_bytes|kubelet_volume_stats_available_bytes|btp_[a-zA-Z_]+"
                    action        = "keep"
                }
            }
        }
        {{- end }}
 ```

**Comment by roderik** [comment] 2024-04-15 09:51
Another one, my guess the schema.gql file

```
2024-04-15T09:14:01.877425Z ERROR commit_virtual_branch: crates/gitbutler-tauri/src/virtual_branches.rs:22: error=Error(error parsing patch: Hunks not in order or overlap) [3mproject_id[0m[2m=[0mb62e0f66-0449-453b-8316-8a2d260176ca [3mbranch[0m[2m=[0m9a7a5b3d-0c56-449d-9f34-ecc457b7dbd2 feat: mainnet metrics [3mownership[0m[2m=[0mSome(BranchOwnershipClaims { claims: [OwnershipClaim { file_path: "apps/app/components/features/blockchain-network-statistics/lib/EthereumMainnetNetworkStatistics.tsx", hunks: [Hunk { hash: Some("f1df95b5ebd80b807f16ea65dcfd27cf"), timestamp_ms: None, start: 59, end: 66 }] }, OwnershipClaim { file_path: "apps/api/src/modules/metrics/lib/services/range/mainnet-range-metric.service.ts", hunks: [Hunk { hash: Some("afd1a4f17e0cee8845775181ada5e09d"), timestamp_ms: None, start: 3, end: 16 }, Hunk { hash: Some("d1962639f56a78d8316365ea76f7ae7d"), timestamp_ms: None, start: 17, end: 25 }, Hunk { hash: Some("b8bb2008421158ae4db3dec28eeb5634"), timestamp_ms: None, start: 26, end: 36 }, Hunk { hash: Some("29d89accf1323de61d0f150cd2e591f7"), timestamp_ms: None, start: 38, end: 93 }] }, OwnershipClaim { file_path: "apps/api/src/modules/metrics/lib/services/instant/mainnet-instant-metric.service.ts", hunks: [Hunk { hash: Some("7c06e975bfd94ee77eb349330882a257"), timestamp_ms: None, start: 2, end: 52 }] }, OwnershipClaim { file_path: "infra/values.prod.1p.yaml", hunks: [Hunk { hash: Some("4216aa236e684efd5622fc8a50fdd01d"), timestamp_ms: None, start: 812, end: 819 }] }, OwnershipClaim { file_path: "apps/api/schema.gql", hunks: [Hunk { hash: Some("677504d566af4a8826b8a25a9193e18e"), timestamp_ms: None, start: 1838, end: 1844 }, Hunk { hash: Some("3bc234fe455f75cbc821dbb9c3735045"), timestamp_ms: None, start: 4463, end: 4469 }, Hunk { hash: Some("f21a429cb5c00e991bcbbb08c05233e0"), timestamp_ms: None, start: 6673, end: 6679 }, Hunk { hash: Some("06d71c7c39dd8d520a6625a5d749e40a"), timestamp_ms: None, start: 6691, end: 6701 }] }, OwnershipClaim { file_path: "apps/api/src/modules/blockchain/processor/lib/pulumi-resources/mainnet/mainnet.resource.ts", hunks: [Hunk { hash: Some("8a5255dd26c0fff2f12b90a44e8b0238"), timestamp_ms: None, start: 1, end: 6 }, Hunk { hash: Some("07153adfef402090764f00de7b04d8af"), timestamp_ms: None, start: 9, end: 19 }, Hunk { hash: Some("285f7594662a458b31c0d2db6f017de0"), timestamp_ms: None, start: 20, end: 35 }, Hunk { hash: Some("c2be186ce89f697919c0aa52c3c4533e"), timestamp_ms: None, start: 41, end: 48 }, Hunk { hash: Some("508dbad8d2a8da21a331f120fac3a1eb"), timestamp_ms: None, start: 66, end: 113 }, Hunk { hash: Some("40df6b53cf566c15d4fb9aef2a53a164"), timestamp_ms: None, start: 150, end: 199 }] }, OwnershipClaim { file_path: "apps/api/src/modules/blockchain/processor/lib/jobs/mainnet-node.processor.ts", hunks: [Hunk { hash: Some("3f4e6292c071640591a8220c9d7a97ce"), timestamp_ms: None, start: 8, end: 41 }, Hunk { hash: Some("f896d23838e8fe1f8cf0bd44083b35a6"), timestamp_ms: None, start: 90, end: 97 }, Hunk { hash: Some("d919a368d62d984521ccbbedbf9d38cc"), timestamp_ms: None, start: 102, end: 112 }] }, OwnershipClaim { file_path: "apps/api/src/modules/entities/index.ts", hunks: [Hunk { hash: Some("3f7e122a9f67d4e583632e262837fc25"), timestamp_ms: None, start: 250, end: 255 }] }, OwnershipClaim { file_path: "charts/settlemint/templates/api/api-secret.yaml", hunks: [Hunk { hash: Some("7428dc8156da2ee70394ff1c4633d802"), timestamp_ms: None, start: 147, end: 154 }] }, OwnershipClaim { file_path: "charts/settlemint/templates/support/supportbundle-secret.yaml", hunks: [Hunk { hash: Some("f544344f1a23fde2efad7d08359a409c"), timestamp_ms: None, start: 128, end: 135 }] }, OwnershipClaim { file_path: "charts/settlemint/values.yaml", hunks: [Hunk { hash: Some("4422d153be31d1661f84b29d981ca72f"), timestamp_ms: None, start: 286, end: 297 }] }] }) [3mrun_hooks[0m[2m=[0mfalse
```

**Comment by roderik** [comment] 2024-04-15 09:54
Oh, "overlapping" made me think of something, in the regex example i added metrics over time to the beginning of the line and i think i committed in between every now and again. That could be an "overlapping" reason i think?

**Comment by mtsgrd** [comment] 2024-04-16 14:38
Based on discord feedback this is likely fixed by: #3451

**Comment by mtsgrd** [comment] 2024-04-18 07:53
The above PR did not make the problem go away, but I have a pretty good idea now about where the gaps are. Instead of tracking overlap manually we should probably lean on `git blame` for answering the question "do any of these new hunks" intersect with a commit in the `target..integration_commit` range.

**Comment by roderik** [comment] 2024-04-18 15:15
I have not had it anymore, fingers crossed

**Comment by Qix-** [comment] 2024-04-30 10:57
@mtsgrd @roderik Is this still an issue? I know a lot of work went into dealing with this and I haven't heard of it happening as of late.

**Comment by mtsgrd** [comment] 2024-04-30 12:07
In theory it should not be happening since the introduction of `get_workspace_head`.  I also haven't heard any reports lately so let's close the issue for now?

**Closed** 2024-04-30 12:11 UTC
Labels: bug, feedback requested
