### ISSUE TITLE
Cannot add project when filetree contains a socket

### ISSUE THREAD

**Issue by To1ne** [gitbutlerapp/gitbutler#3614] opened 2024-04-26 10:41 UTC
I tried to import my project, in the project directory there is a socket file (which is in the `.gitignore`) which is used to run the project locally. Having this socket in existence makes project import fail:

```
2024-04-26T08:44:54.072686Z  INFO add_project: gitbutler-app/src/projects/commands.rs:71: close time.busy=18.1s time.idle=50.0µs [3mpath[0m[2m=[0m"/home/toon/devel/gdk"
2024-04-26T08:46:30.743736Z  INFO add_project: gitbutler-app/src/projects/commands.rs:71: new [3mpath[0m[2m=[0m"/home/toon/devel/gdk"
2024-04-26T08:46:30.746217Z  INFO add_project: gitbutler-app/src/gb_repository/repository.rs:343: created new session project_id=b68db585-dcaa-4ec3-9a04-6ada8c80db80 session_id=0df76f79-4ce5-418e-a598-827132d46abd [3mpath[0m[2m=[0m"/home/toon/devel/gdk"
2024-04-26T08:46:46.720936Z ERROR add_project: gitbutler-app/src/projects/commands.rs:63: failed to add project error=failed to open repository

Caused by:
    0: failed to run initial flush
    1: failed to build working directory tree
    2: failed to build wd index
    3: failed to add working directory path gitlab.socket
    4: could not open '/home/toon/devel/gdk/gitlab.socket': No such device or address; class=Os (2) [3mpath[0m[2m=[0m"/home/toon/devel/gdk"
2024-04-26T08:46:46.720972Z  INFO add_project: gitbutler-app/src/projects/commands.rs:71: close time.busy=16.0s time.idle=41.0µs [3mpath[0m[2m=[0m"/home/toon/devel/gdk"
```

You can clone the project from https://gitlab.com/gitlab-org/gitlab-development-kit/, but you need to run the whole SDK to run into this, so I've created reproduction steps:

```sh
git init my-project
cd my-project
nc -lU my.socket
```

Try to import that, and you'll get "Something went wrong".

---

While I was testing this I noticed import seems to hang when you have a named pipe in your repo, created with `mkfifi my.pipe`.

**Comment by Byron** [comment] 2024-04-26 12:49
Thanks for reporting!

It looks like you are on Windows and aren't using the latest version, 0.11.4 at the moment. There the issue you are describing should be fixed. Could you try to update and try again? Thank you.

**Comment by To1ne** [comment] 2024-04-26 13:44
I'm on Linux. Maybe I wasn't using 0.11.4 at the time, but now I am. The log now shows:

```
2024-04-26T13:42:33.040736Z ERROR add_project: crates/gitbutler-tauri/src/projects.rs:27: error=Error(failed to add 'foo.socket' to temporary index

Caused by:
    0: failed to open repository
    1: failed to run initial flush
    2: failed to build working directory tree
    3: failed to build wd index
    4: failed to add 'foo.socket' to temporary index
    5: could not open '/tmp/tmp.PdmNlywACH/foo.socket': No such device or address; class=Os (2)) [3mpath[0m[2m=[0m"/tmp/tmp.PdmNlywACH"
2024-04-26T13:42:33.040780Z  INFO add_project: crates/gitbutler-tauri/src/projects.rs:27: close time.busy=16.7ms time.idle=57.7µs [3mpath[0m[2m=[0m"/tmp/tmp.PdmNlywACH"
```

**Comment by Qix-** [comment] 2024-04-30 10:20
I actually can't reproduce this on MacOS. Not only does our client ignore it, but even the Git CLI ignores it entirely, even without a `.gitignore`.

**Comment by jhult** [comment] 2024-05-06 16:17
Possibly related issues: #2608 and #2672

**Comment by krlvi** [comment] 2024-11-01 09:05
I believe this was resolved together with this issue https://github.com/gitbutlerapp/gitbutler/issues/2672 
Does this still present an issue for anybody? I will close the issue otherwise

**Comment by krlvi** [comment] 2024-11-08 22:09
Closing this since I believe this is fixed and haven't heard back. Feel free to open a new issue if this still presents a problem

**Closed by krlvi** 2024-11-08 22:09 UTC
Labels: bug, feedback requested
