### ISSUE TITLE
GitButler Authentication does not work

### ISSUE THREAD

**Issue by HakanKorkz** [gitbutlerapp/gitbutler#5461] opened 2024-11-06 06:41 UTC
### Version

0.13.10

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

![Ekran görüntüsü 2024-11-06 093058](https://github.com/user-attachments/assets/9e6579ce-67e0-4359-8f76-62f1f5b38a20)

Due to recent updates, I am unable to use gitButler, including the inability to link to my GitHub account. 

I uninstalled and reinstalled the program, and performed a clean installation of the Windows registry.

**Comment by Byron** [comment] 2024-11-06 07:07
Thanks a lot for reporting!

There are a couple of related issues that I link up for completeness:

* #5457 
* #5456 

And another one which seems to be the same one as reported here, possibly a duplicate.

* #5460 

I think in a related issue I already linked @estib-vega for help, and I will do the same here in case all of these are related.

**Comment by krlvi** [comment] 2024-11-06 09:30
Hey, thank you for reporting! We have a hypothesis that the issue is related to the Tauri v1 to v2 upgrade. It appears that the `origin` for initiated requests is different between the versions (only on Windows). 
We are deploying a fix to the webapp that handles auth and if this hypothesis is correct, it should start working without the need for an app update (I added the apparently new CORS origin to the list)

**Comment by krlvi** [comment] 2024-11-06 10:16
> I am grateful for your return and interest.

Of course! Thank you for taking the time to create a Github issue!
Are you able to re-test now? I believe the issue should be fixed (I tested via a windows VM)

**Comment by HakanKorkz** [comment] 2024-11-07 10:22
Thank you for your inquiry. I am pleased to inform you that the issue has been resolved. Due to the volume of work, I was unable to provide feedback at the time. I appreciate your interest and concern.

**Closed** 2024-11-07 15:10 UTC
Labels: bug, os:windows, feedback requested, auth*
