### ISSUE TITLE
commits are not signed when using git executable as authentication strategy

### ISSUE THREAD

**Issue by kaoths** [gitbutlerapp/gitbutler#3311] opened 2024-03-25 10:03 UTC
I have these git configs set on my machine
```
gpg.format=ssh
commit.gpgsign=true
```

However, when I commit changes from the GitButler's lanes and push them to the remote repository, GitHub does not show `verified` (with vigilant mode off) on those commits; it shows nothing.  
With vigilant mode on, it shows 'unverified'.  

<hr />

git version: 
2.42.0  

GitButler version: 
0.10.27  

OS:  
MacOS 14.4 (Appli Silicon)

**Comment by Akasiek** [comment] 2024-03-28 11:49
It seems that GitButler will not sign commits with a configured GPG or SSH key. 

There is an option to use GitButler's own SSH key to sign commits, but I would prefer it to just use my GPG key, which is already working.

**Comment by Byron** [comment] 2024-04-23 11:15
Thanks for reporting!

I am closing this as duplicate of (the newly created) #3586, after adding the key difference from this issue regarding the "Use Git executable" authentication option. You are very welcome to subscribe there and contribute.

**Closed by Byron** 2024-04-23 11:15 UTC
Labels: bug, duplicate, UX
