### ISSUE TITLE
Workspace stuck loading

### ISSUE THREAD

**Issue by nathanael-ruf** [gitbutlerapp/gitbutler#2657] opened 2024-02-14 07:20 UTC
When I first tried GitButler it worked as expected. I then closed it, worked with git branches as usual and later opened GitButler again. It then prompted me to switch back to its branch which I accepted. Now it's just showing a loading spinner where the workspace branches normally are.
I can still see the trunk and the remote branches on the left. 
A `git status` shows pretty much every file in the repo as `new file`, so not sure what it's doing. Restart doesn't help.
It's a real bummer because I "stashed" a virtual branch that is now unretrievable.

Let me know if I can provide more info somehow.
Is GitButler store some state for a repo somewhere that I can manually delete?

**Comment by CarlosZiegler** [comment] 2024-02-14 07:46
Same here, still loading

**Comment by Byron** [comment] 2024-04-21 14:35
To me this sounds like an error occurred, but the UI didn't notice it keeps waiting for a successful response that never arrives.

Is there errors in [the logs](https://docs.gitbutler.com/development/debugging#logs) you could share?

**Comment by dlejay** [comment] 2024-05-06 17:50
I have never been able to see the “Workspace” part of the app, only the loading spinner.

Here is the tail of the log
```
2024-05-06T17:46:02.512024Z  INFO handle: crates/gitbutler-watcher/src/handler/mod.rs:70: new event=GitFileChange(a93a347c-39a1-48f9-9fbd-741efca4b4ca, FETCH_HEAD)
2024-05-06T17:46:02.512080Z  INFO handle:calculate_virtual_branches: crates/gitbutler-watcher/src/handler/mod.rs:162: new event=GitFileChange(a93a347c-39a1-48f9-9fbd-741efca4b4ca, FETCH_HEAD)
2024-05-06T17:46:02.512548Z  INFO list_remote_branches: crates/gitbutler-tauri/src/virtual_branches.rs:439: new project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
2024-05-06T17:46:02.551819Z  WARN list_remote_branches: crates/gitbutler-core/src/virtual_branches/remote.rs:117: ignoring branch Some("refs/remotes/origin/HEAD") as peeling failed err=NotFound(Error { code: -3, klass: 3, message: "the reference 'refs/remotes/origin/HEAD' cannot be peeled - Cannot resolve reference" }) project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
2024-05-06T17:46:02.551937Z  INFO list_remote_branches: crates/gitbutler-tauri/src/virtual_branches.rs:439: close time.busy=39.4ms time.idle=10.0µs project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
2024-05-06T17:46:02.613757Z  INFO get_base_branch_data: crates/gitbutler-tauri/src/virtual_branches.rs:104: new project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
2024-05-06T17:46:02.653396Z  INFO get_base_branch_data: crates/gitbutler-tauri/src/virtual_branches.rs:104: close time.busy=39.6ms time.idle=22.2µs project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
2024-05-06T17:46:02.655417Z  INFO list_remote_branches: crates/gitbutler-tauri/src/virtual_branches.rs:439: new project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
2024-05-06T17:46:02.694873Z  WARN list_remote_branches: crates/gitbutler-core/src/virtual_branches/remote.rs:117: ignoring branch Some("refs/remotes/origin/HEAD") as peeling failed err=NotFound(Error { code: -3, klass: 3, message: "the reference 'refs/remotes/origin/HEAD' cannot be peeled - Cannot resolve reference" }) project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
2024-05-06T17:46:02.695008Z  INFO list_remote_branches: crates/gitbutler-tauri/src/virtual_branches.rs:439: close time.busy=39.6ms time.idle=13.5µs project_id=a93a347c-39a1-48f9-9fbd-741efca4b4ca
```

**Comment by stijnvanderlaan** [comment] 2024-05-23 08:25
Same problem here, no errors in log. I have 378 changes, a lot, but not crazy.

**Comment by Byron** [comment] 2024-05-23 11:23
Thanks for sharing! The logs feel like it's doing the same thing over and over again, and it's getting into some self-inflicted loop - a filesystem change triggers an action, that triggers a filesystem change again, …..

378 changes aren't a problem, I believe, it's something else.

Oh, now that I remember this, when opening the Linux kernel it took 2 hours because it went through all the history to eagerly fetch profile pictures. Maybe the same is happening here?

This would mean that opening the repository on a clone created with `git clone --depth 1` would work. Maybe that's something you could try?

**Comment by stijnvanderlaan** [comment] 2024-05-23 12:29
Also creating a new branch didn't work until I stacked all changes. Than it created al lot of branches because I clicked a lot on the "new branch" button when it was unresponsive.

**Comment by stijnvanderlaan** [comment] 2024-05-23 15:11
I think it has something to do with a large modified yarn.lock file. Other changes are fine, but my lock file is 40.000 lines, with a lot of diffs.

**Comment by Byron** [comment] 2024-05-23 16:50
Thank you! Indeed I have also heard that large diffs (or small diffs of large files?) can take a long time to compute.

And since this issue isn't about 'stuck loading after adding project', I think there is no need to see if `git clone --depth 1` changes anything.

**Comment by Byron** [comment] 2024-05-25 15:21
Since I reproduced it on Windows, I thought I'd look into it, but couldn't see what the actual problem is except for an issue with a project watcher not being available, something that might be more related to a race than anything else.

The endless-spinner I saw was unrelated to big files or big repositories, but something very else and I couldn't make sense of it. I could, however, catch on video what happened here.

https://github.com/gitbutlerapp/gitbutler/assets/63622/ce921d45-6dcb-4847-aa22-2587b440da58

The setup is the latest `master` with [modifications from here](https://github.com/gitbutlerapp/gitbutler/issues/3601#issuecomment-2131271029), and exactly the same state compiled as release binary. The release binary has issues with watching files, apparently, and shows the endless spinner, whereas the debug-dev version has no such issues. Further, once the dev version change the vbranches once, the nightly build would at least be able to open the project again. However, trying to change anything with it would do nothing, and then result in an endless spinner.

**Comment by Byron** [comment] 2024-05-26 07:28
#3865 was merged which will fix one particular reason for UI timeouts.
Timeouts due to performance issues aren't covered by this, but it's a step in the right direction.

If one of you can produce a sample repo that shows the performance issue, I'd love to get my hands on it as it should then be fixable one way or another.

**Comment by stijnvanderlaan** [comment] 2024-05-27 07:32
Great you looking into this! I'm on MacOS btw.

**Comment by Byron** [comment] 2024-05-28 07:24
If you are on nightly, this could already work for you. But if it doesn't and there is high-CPU usage, it's probably a performance issue and it would be great if the file (like `yarn.lock`) could be shared so I can test with it.

**Comment by stijnvanderlaan** [comment] 2024-05-28 09:31
Oh yes, nightly does not crash with the same lock file, works a lot faster!

**Comment by Byron** [comment] 2024-05-28 17:01
That's great, and also interesting, at least it wasn't me who fixed it, probably 😁.

**Comment by krlvi** [comment] 2024-09-10 18:23
Im glad to hear this is fixed! Feel free to create another issue if you come across any other problems. Thanks

**Closed by krlvi** 2024-09-10 18:23 UTC
Labels: bug, performance, UX, feedback requested
