### ISSUE TITLE
Feature Request: Ability to Split Hunks

### ISSUE THREAD

**Issue by aramikuto** [gitbutlerapp/gitbutler#3043] opened 2024-03-06 07:01 UTC
It would be useful to have the ability to split a single hunk into different virtual branches.

For example, if the change involves:
```js
import { featureA } from "src/featureA"

initFeatureB(...)
```
There is currently no way to separate the lines `import { featureA } from "src/featureA"` and `initFeatureB(...)` into separate virtual branches.

**Comment by schacon** [comment] 2024-03-06 12:21
Hey @aramikuto,

We agree that this is something we need to do, but the issue with having subhunk splitting in multiple branches is that it by definition creates a merge conflict between the two independent branches created.

Here is our existing issue for that: https://github.com/gitbutlerapp/gitbutler/issues/2513

I'm closing this as a duplicate of that, but if you want to understand why it's a little difficult, you can read that one.

Thanks!

**Closed by schacon** 2024-03-06 12:21 UTC
