### ISSUE TITLE
Can't log-in or sign-up to profile

### ISSUE THREAD

**Issue by dennist12** [gitbutlerapp/gitbutler#5457] opened 2024-11-05 22:51 UTC
###  Version
0.13.9

### Operating System
Windows 10

### Describe the issue

I can't log in after signing out of my account.

![image](https://github.com/user-attachments/assets/4998e341-c652-4ee4-b65f-20f752de4cea)

**Comment by Byron** [comment] 2024-11-06 06:37
Thanks a lot for reporting!

I was able to reproduce the issue as follows:

* sign out of the GitButler account
* go the AI settings pane of the project settings
* click the login button there
* a browser window pops up where you can login or it uses an existing login, to say that the login was successful
* back to GitButler, nothing seems to have changed, but that error shows up in the console.

Now it gets interesting.

When going to the account/personal profile settings, there will be this toast waiting.

<img width="516" alt="Screenshot 2024-11-06 at 07 32 23" src="https://github.com/user-attachments/assets/8f15fc34-b0d6-43fe-961b-06eb07d75860">

However, it will also show that a login is present.

After all, the login worked but the UI failed to display it due to the CORS issue maybe. For all I can see, the login is correct and refreshing the UI will keep showing the new login.

A login is also possible, without error, from the account/personal profile settings.

CC  @estib-vega who can probably fix it in a jiffy.

**Comment by estib-vega** [comment] 2024-11-06 08:36
@Byron Thanks for tagging me 👍 
This seems to be two-fold issue

@dennist12 Could you try if updating to 0.13.10 fixes your issue?
We discovered that 0.13.9 introduces a bug that CORS errors. We've fixed it in 0.13.10.

The one provided by you @Byron seems to be a FE issue. We seem to be missing a guard. I'll look for that and fix that

**Comment by estib-vega** [comment] 2024-11-06 09:43
@dennist12 This seems to have been actually another thing related to our service headers.
If you update to 0.13.10 and give it a try again, it should be working again

**Comment by dennist12** [comment] 2024-11-06 14:15
@estib-vega Works fine in v0.13.11. Thanks!

**Comment by krlvi** [comment] 2024-11-06 17:56
> @estib-vega Works fine in v0.13.11. Thanks!

Thanks for confirming. Closing this issue then

**Closed by krlvi** 2024-11-06 17:56 UTC
Labels: UI, feedback requested, auth*, 🎉reproduced🎉
