### ISSUE TITLE
Unclear error when pushing GitHub workflow files via HTTP auth

### ISSUE THREAD

**Issue by Timpan4** [gitbutlerapp/gitbutler#2886] opened 2024-02-23 09:45 UTC
I'm trying to update a private repo with a .github publish.yml file and update package.json.

When commiting both and trying to push it just loads while pressing the "Push to remote" button. After loading it continues to say "Push to remote". For some reason this issue only applies to pushes to github. When pushing to bitbucket i can't reproduce this.

Here's the logs from after pressing push to remote for yaml file pushing

```

2024-02-23T09:38:23.695267Z  INFO push_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:330: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mfalse
2024-02-23T09:38:23.984979Z  INFO push_virtual_branch: gitbutler-app/src/git/credentials.rs:63: authenticating with https://github.com/c1-ab/c1-eslint-plugin.git using github token [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mfalse
2024-02-23T09:38:24.549560Z  INFO push_virtual_branch: gitbutler-app/src/project_repository/repository.rs:373: pushed git branch project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 remote=origin head=7cb555e43a6a2b6f66a3d64209eb21cb6e7f0135 branch="Add-github-packages-publish-workflow-1" [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mfalse
2024-02-23T09:38:24.852417Z  INFO push_virtual_branch: gitbutler-app/src/git/credentials.rs:63: authenticating with https://github.com/c1-ab/c1-eslint-plugin.git using github token [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mfalse
2024-02-23T09:38:25.047331Z  INFO push_virtual_branch: gitbutler-app/src/project_repository/repository.rs:422: git fetched project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 refspec=+refs/heads/*:refs/remotes/origin/* [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mfalse
2024-02-23T09:38:25.047627Z  INFO push_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:330: close time.busy=1.35s time.idle=68.8µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mfalse
2024-02-23T09:38:25.048892Z  INFO list_virtual_branches: gitbutler-app/src/virtual_branches/commands.rs:74: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.083290Z  INFO list_virtual_branches: gitbutler-app/src/virtual_branches/commands.rs:74: close time.busy=18.0ms time.idle=16.5ms [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.085121Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:38:25.085904Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:38:25.086164Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: close time.busy=1.03ms time.idle=18.5µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:38:25.086977Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=1.06ms time.idle=20.0µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:38:25.177006Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/FETCH_HEAD
2024-02-23T09:38:25.177061Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/logs/HEAD
2024-02-23T09:38:25.177197Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/index
2024-02-23T09:38:25.178996Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.182191Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: close time.busy=3.17ms time.idle=29.8µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.203343Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:38:25.203833Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:38:25.204392Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: close time.busy=1.03ms time.idle=31.3µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:38:25.204972Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=1.12ms time.idle=20.2µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:38:25.206547Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/logs/HEAD
2024-02-23T09:38:25.206579Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/index
2024-02-23T09:38:25.279291Z  INFO get_base_branch_data: gitbutler-app/src/virtual_branches/commands.rs:159: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.280924Z  INFO get_base_branch_data: gitbutler-app/src/virtual_branches/commands.rs:159: close time.busy=1.61ms time.idle=31.0µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.282130Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.282952Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: close time.busy=810µs time.idle=15.5µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:38:25.324596Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/logs/HEAD
2024-02-23T09:38:25.324665Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/index
```

Here's the logs while pushing without yaml

```
2024-02-23T09:45:16.445550Z  INFO push_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:330: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mtrue
2024-02-23T09:45:16.750355Z  INFO push_virtual_branch: gitbutler-app/src/git/credentials.rs:63: authenticating with https://github.com/c1-ab/c1-eslint-plugin.git using github token [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mtrue
2024-02-23T09:45:17.550715Z  INFO push_virtual_branch: gitbutler-app/src/project_repository/repository.rs:373: pushed git branch project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 remote=origin head=f5e95575f6499787dc643b52192af0ad4a871cbe branch="Add-github-packages-publish-workflow-1" [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mtrue
2024-02-23T09:45:17.849692Z  INFO push_virtual_branch: gitbutler-app/src/git/credentials.rs:63: authenticating with https://github.com/c1-ab/c1-eslint-plugin.git using github token [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mtrue
2024-02-23T09:45:18.073330Z  INFO push_virtual_branch: gitbutler-app/src/project_repository/repository.rs:422: git fetched project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 refspec=+refs/heads/*:refs/remotes/origin/* [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mtrue
2024-02-23T09:45:18.075153Z  INFO push_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:330: close time.busy=1.63s time.idle=121µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33" [3mwith_force[0m[2m=[0mtrue
2024-02-23T09:45:18.078198Z  INFO list_virtual_branches: gitbutler-app/src/virtual_branches/commands.rs:74: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.118235Z  INFO list_virtual_branches: gitbutler-app/src/virtual_branches/commands.rs:74: close time.busy=11.8ms time.idle=28.3ms [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.119587Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:45:18.120342Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:45:18.120544Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: close time.busy=937µs time.idle=26.7µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:45:18.121503Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=1.15ms time.idle=16.2µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:45:18.206051Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/FETCH_HEAD
2024-02-23T09:45:18.206109Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/logs/HEAD
2024-02-23T09:45:18.207421Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.208409Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: close time.busy=971µs time.idle=23.2µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.217904Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:45:18.218818Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:45:18.220345Z  INFO can_apply_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:354: close time.busy=2.42ms time.idle=26.7µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mbranch_id[0m[2m=[0m"cea62d45-040b-4b37-9195-24fd63a73d33"
2024-02-23T09:45:18.220701Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=1.87ms time.idle=38.7µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0" [3mrefname[0m[2m=[0m"refs/remotes/origin/Add-github-packages-publish-workflow-1"
2024-02-23T09:45:18.236099Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/logs/HEAD
2024-02-23T09:45:18.236142Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/index
2024-02-23T09:45:18.308138Z  INFO get_base_branch_data: gitbutler-app/src/virtual_branches/commands.rs:159: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.309918Z  INFO get_base_branch_data: gitbutler-app/src/virtual_branches/commands.rs:159: close time.busy=1.75ms time.idle=37.2µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.311384Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: new [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.312636Z  INFO list_remote_branches: gitbutler-app/src/virtual_branches/commands.rs:504: close time.busy=1.24ms time.idle=21.4µs [3mproject_id[0m[2m=[0m"e49bd170-ca68-4fdf-9e30-cd2ea198faa0"
2024-02-23T09:45:18.322658Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/logs/HEAD
2024-02-23T09:45:18.322712Z  INFO gitbutler-app/src/watcher/dispatchers/file_change.rs:103: git file change project_id=e49bd170-ca68-4fdf-9e30-cd2ea198faa0 file_path=.git/index
```

**Comment by abkfenris** [comment] 2024-02-25 20:04
I'm having the same issue, but I'm getting an error in the logs in addition to the generic message in the client.

<img width="376" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/1296209/03e9ff7b-d7db-49ba-87c1-17926be2cd3e">

```
2024-02-25T20:00:08.225674Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Remove-Pages_old"
2024-02-25T20:00:08.226288Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/consolidate-stream-pages"
2024-02-25T20:00:08.226800Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Update-pre-commit-hooks"
2024-02-25T20:00:08.227222Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Remove-React-Router-formatting"
2024-02-25T20:00:08.227786Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/dependabot/npm_and_yarn/frontend/apollo/experimental-nextjs-app-support-0.8.0"
2024-02-25T20:00:08.227977Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: new project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Add-embed-support-to-richtextblock"
2024-02-25T20:00:08.238573Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=12.2ms time.idle=69.7µs project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/consolidate-stream-pages"
2024-02-25T20:00:08.238596Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=10.5ms time.idle=102µs project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Add-embed-support-to-richtextblock"
2024-02-25T20:00:08.238668Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=10.8ms time.idle=78.1µs project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/dependabot/npm_and_yarn/frontend/apollo/experimental-nextjs-app-support-0.8.0"
2024-02-25T20:00:08.238690Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=11.4ms time.idle=55.5µs project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Remove-React-Router-formatting"
2024-02-25T20:00:08.238730Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=11.9ms time.idle=32.4µs project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Update-pre-commit-hooks"
2024-02-25T20:00:08.238958Z  INFO get_remote_branch_data: gitbutler-app/src/virtual_branches/commands.rs:521: close time.busy=13.2ms time.idle=68.2µs project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" refname="refs/remotes/origin/Remove-Pages_old"
2024-02-25T20:00:13.529460Z  INFO push_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:330: new project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" branch_id="42ee0211-9917-4c4c-8223-a18a13153b49" with_force=false
2024-02-25T20:00:13.837501Z  INFO push_virtual_branch: gitbutler-app/src/git/credentials.rs:63: authenticating with https://github.com/gulfofmaine/VSNext.git using github token project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" branch_id="42ee0211-9917-4c4c-8223-a18a13153b49" with_force=false
2024-02-25T20:00:14.427651Z ERROR push_virtual_branch: gitbutler-app/src/project_repository/repository.rs:474: error=git_push_status_foreach callback returned -1; class=Callback (26) project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" branch_id="42ee0211-9917-4c4c-8223-a18a13153b49" with_force=false
2024-02-25T20:00:14.427687Z  INFO push_virtual_branch: gitbutler-app/src/virtual_branches/commands.rs:330: close time.busy=898ms time.idle=50.3µs project_id="5d8b6056-4266-45fb-b422-93f84e947c9e" branch_id="42ee0211-9917-4c4c-8223-a18a13153b49" with_force=false
```

I tried un-applying all my other virtual branches and this one is still erroring on push.

**Comment by abkfenris** [comment] 2024-03-05 18:04
I was however able to push a `.github/dependabot.yml`, at least as of Version 0.10.22 (20240305.143047) The previous error I was getting was with `.github/workflows/push.yml`.

**Comment by anirudhsama** [comment] 2024-03-22 07:15
Ran into the same issue and after debugging, it that the issue is Gitbutler is using https basic auth, you can see that in the log line:

```2024-02-27T18:15:14.841272Z  INFO push_virtual_branch: gitbutler-app/src/git/credentials.rs:63: authenticating with https://github.com/<org>/<repo>.git using github token project_id="ef35381d-354f-4d12-b7f4-8b197265a4fd" branch_id="dd346346-1cba-46e4-b4eb-0c5318d26af2" with_force=false```

Github basic auth uses Personal Access Tokens, and if that token doesn't have permissions to edit workflows, Github will not allow to create the PR/make changes to the workflow.yml file. To get around it, change the authentication method to SSH.

**Comment by krlvi** [comment] 2024-03-23 20:58
Hey, so I think i got to the bottom of this - there was an error in the `push_update_reference` callback that libgit2 seems to not propagate, and it was never surfacing. 
Fixed the visibility issue here: https://github.com/gitbutlerapp/gitbutler/pull/3295

And this is how the error will look from the next release
<img width="499" alt="Screenshot 2024-03-23 at 21 39 22" src="https://github.com/gitbutlerapp/gitbutler/assets/4030927/7b8133b3-4dfe-4730-b3b7-3bb7b54cbf84">

GitHub rejects the push because it wants an extra scope on the oauth. The solution here would be to either add an additional scope to the oauth app (the workflow scope in particular) or to simply encourage people to use another auth configuration. I am leaning towards the second option so that we can have the GH scopes as minimal as possible.

**Comment by Byron** [comment] 2024-04-22 15:31
I have looked into this and created a PR which would help the UI to show a specific message to help with this case. It's notable though the it's still undefined to the frontend why exactly the remote rejected a push, there are many possible reasons, so that message would probably be somewhat general, or mentions the typical reasons.

**Comment by krlvi** [comment] 2024-08-16 11:53
I think this issue should be fixed now. Specifically, regarding pushing, the app now fork-execs to the git binary which has eliminated many of the issues that we were seeing in the past. Closing this issue now, but feel free to open a new one if you encounter any problems

**Closed by krlvi** 2024-08-16 11:53 UTC
Labels: bug
