### ISSUE TITLE
super slow in a windows 10 virtual machine with no Internet

### ISSUE THREAD

**Issue by hanchao0606** [gitbutlerapp/gitbutler#4007] opened 2024-06-05 13:13 UTC
Not suitable for larger projects? When vscode source code is super slow

**Comment by hanchao0606** [comment] 2024-06-05 13:23
final tip：Timed out while reloading virtual branches

**Comment by Byron** [comment] 2024-06-05 15:31
Do you mean the opening the source-repository of vscode is slow? And further, which platform are you on?

Is it correct I assume that you are on the latest release version v0.12?

Thanks for providing more context.

**Comment by hanchao0606** [comment] 2024-06-06 02:06
@Byron  Using Gitbutler to open the local Visual Studio Code source code on Windows 10 is very slow

**Comment by hanchao0606** [comment] 2024-06-06 02:06
> Hey! We have created a performance regression with the 0.12.0 release. There is one fix that is currently being tested, and if all is good, will have it as part of the next patch. If you would like to test it out before it's ready, you could try out the latest nightly release (from https://app.gitbutler.com/downloads) and enable the "_Use new experimental hunk locking algorithm_" config: <img alt="image" width="1175" src="https://private-user-images.githubusercontent.com/4030927/336957057-2d5d447b-943d-45cf-bcee-979055ba716e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzgyODgsIm5iZiI6MTcxNzYzNzk4OCwicGF0aCI6Ii80MDMwOTI3LzMzNjk1NzA1Ny0yZDVkNDQ3Yi05NDNkLTQ1Y2YtYmNlZS05NzkwNTViYTcxNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDEzOTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY4NzFlOWQ3YjliNzczNTQxZWIyMjc1Y2Q5ZTBkMzc0YzQ5ZDc0NTQyYTc3YmNkNWVkOTc1MjViNzI5NjNhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rkSSC29oeHfGvdE3qle_RbpaQFTeK94mgzHfUSJpNwY">

@krlvi I'll give it a try

**Comment by Byron** [comment] 2024-06-06 09:31
> @Byron Using Gitbutler to open the local Visual Studio Code source code on Windows 10 is very slow

Great, thanks, I will give that a try as well.

**Comment by hanchao0606** [comment] 2024-06-06 12:41
@Byron Thank you very much for your reply. I really like this software. Today, I reopened it and found it not as slow as before. However, it is still very slow on my company's computer. The company uses an intranet and cannot connect to the internet. (It's extremely slow. After adding a company project, it takes an hour to load the homepage. Once inside, many actions don't respond, likely due to the slowness. I tried several versions and it's the same.) I would like to ask if this software can be used in an intranet environment?  Windows 10

**Comment by krlvi** [comment] 2024-06-06 21:41
Just released a patch version `0.12.2` which has this fix enabled by default. I hope this helps, and at the same time, we are working on one more performance optimization which will land in a few days hopefully

**Comment by hanchao0606** [comment] 2024-06-07 01:11
@krlvi  Thank you very much for your reply, but 0.12.2 is still very slow, and this page will take a long time. What information can I provide you with?
![1717722486634](https://github.com/gitbutlerapp/gitbutler/assets/22366546/968fa722-6b26-44c4-83bc-4698d0c40458)

**Comment by Byron** [comment] 2024-06-07 07:05
Thanks a lot for the context!

Now that you are saying it: hour-long waiting times without CPU would definitely hint at a networking issue. The UI is likely to require resources of the internet, which is something I noticed when using a VM that had something like a 60s delay before a host could be resolved.
I also noticed that at least  a couple of weeks ago it would load gravatar profile pictures of all authors in the history before showing the project.

Is gravatar reachable for you?
But maybe there are also other resources, like fonts, which it tries to get from a google server.

**Comment by krlvi** [comment] 2024-06-07 08:46
@hanchao0606 is it possible that this solution from the other thread works for you too? https://github.com/gitbutlerapp/gitbutler/issues/3807#issuecomment-2144989180

**Comment by krlvi** [comment] 2024-06-07 09:40
@anaisbetts do you have a hunch what could be causing this black screen situation?

**Comment by hanchao0606** [comment] 2024-06-07 12:10
@krlvi  Thank you very much for your reply; the WebView2 link you gave needs to be installed with a network connection. I installed the complete installation package of WebView2 before installing gitbutler.

This is not a black screen, this is the loading main page. The black screen is because I set the software to dark mode; I don’t know what caused it; I can only provide some information and details that I know; first of all, the environment is internal Network, cannot access the Internet, the computer is a virtual machine Windows 10; then it will take a long time to switch from other pages in the software to the main page

**Comment by anaisbetts** [comment] 2024-06-07 14:58
@krlvi I would tend to agree with @Byron, this isn't an OS issue it's a networking issue, maybe try tethering to replicate his environment a bit?

**Comment by krlvi** [comment] 2024-06-07 15:29
weird, i use the app quite often on flights with no internet. im gonna dig some more into this

**Comment by hanchao0606** [comment] 2024-06-09 02:09
Push and Apply also don’t work and the error message is as follows:
![cd84ed0bd38a77b4013dab60f5719dd](https://github.com/gitbutlerapp/gitbutler/assets/22366546/da2167c7-2187-4b3b-bf89-0da78360aff3)

**Comment by krlvi** [comment] 2024-06-09 09:17
> Push and Apply also don’t work and the error message is as follows: ![cd84ed0bd38a77b4013dab60f5719dd](https://private-user-images.githubusercontent.com/22366546/337941367-da2167c7-2187-4b3b-bf89-0da78360aff3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjQ4NzYsIm5iZiI6MTcxNzkyNDU3NiwicGF0aCI6Ii8yMjM2NjU0Ni8zMzc5NDEzNjctZGEyMTY3YzctMjE4Ny00YjNiLWJmODktMGRhNzgzNjBhZmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA5MTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZGY4ZGQ5ZGM0Y2RkYThkN2I0OGNmODNlM2M1ZWUwMjA1MzQ1MDg3ZTc3YTc4Y2VmNDNkMTA3MTlkNTkxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2n0Jw2RGp9B4TViKun_dl0cweGHv6RaP2hRHltKYf40) Is it related to slowness?

sounds possible. Is there a chance that there is no git executable installed on that windows VM? Especially on Windows, GitButler needs the git binary to be installed

**Comment by hanchao0606** [comment] 2024-06-09 09:49
@krlvi  In the app startup log, it keeps trying to connect to this address https://www.gravatar.com/avatar/c2c0cbe6684b43fd7450acdf8cf911f.
 It will not display normally until it no longer tries to connect
git
I'm sure git is already installed, is it possible that you don't have permission to run it?

**Comment by krlvi** [comment] 2024-06-09 19:49
Thanks for this stack trace this was indeed helpful. The app tries to do assets caching for performance but now I am realizing that the way this is implemented can cause blocking, like in your case. 
I added a timeout to that mechanism here - https://github.com/gitbutlerapp/gitbutler/pull/4047 (will be part of the next release) which should help this situation. 
At the same time, we should probably re-consider how we approach assets caching and have it not on path of execution of application logic. 
(fyi @Byron )

**Comment by hanchao0606** [comment] 2024-06-09 21:33
@krlvi  Thanks you very mach for your replay。 Can the situation of being unable to execute git be resolved?  I've already installed git

**Comment by hanchao0606** [comment] 2024-06-18 08:51
Hi @krlvi   It's still very slow now, can this request be removed? Or can you give me a separate installation package without this request?
[1718700468986](https://github.com/gitbutlerapp/gitbutler/assets/22366546/68cfbdd3-7da5-4e7e-a7f9-72865ac98713)

**Comment by Byron** [comment] 2024-06-19 05:23
I think the issue isn't the timeout (which I believe should remain with the default), but that the frontend seemingly waits for the request to be finished before continuing. Ideally, that runs in the background, very much like a browser would download and fill in resources on the fly.

**Comment by hanchao0606** [comment] 2024-06-20 12:32
@ndom91 Thanks you very mach for your replay。There seems to be no problem
![1718886365281](https://github.com/gitbutlerapp/gitbutler/assets/22366546/20782c29-39c7-4d02-9dc4-d04cccabb88b)

**Comment by ndom91** [comment] 2024-06-20 12:48
@Byron ahh this proxy is in the Rust side of things (see the `assets.rs` file). Definitely not my wheelhouse :sweat_smile:

**Comment by Byron** [comment] 2024-06-20 19:09
@ndom91 Oh, right, and I thought it's used by the frontend for some reason, but it's well able to fetch assets by itself, I see :D.
Then we might be back to square one as it's unclear what's causing these delays, or what the assets are that are being downloaded. I know of gravatar images that previously blocked, but that might have changed already.

@hanchao0606 Could it be that the PATH isn't adjusted system-wide? Sometimes terminals come up with a different PATH than will be used by windowed applications. I also don't know if a windowed application would inherit the PATH of the terminal if it would be launched from there. If that doesn't work, maybe you can double-check that [the system path](https://www.c-sharpcorner.com/article/how-to-addedit-path-environment-variable-in-windows-11/) contains the Git executable.

**Comment by ndom91** [comment] 2024-06-21 10:27
@Byron yeah I thoguht it'd be a frontend thing too. Tbh, I'm not sure why it's being done in Rust actually, if it were a simple image fetched on the frontend we could take advantage of all the built-in browser caching and probably not need that additional rust `Proxy` wrapper and extra caching logic, no? :thinking:

**Comment by ndom91** [comment] 2024-06-21 10:28
I know the AppImage, for example, uses a different `$PATH` from the desktop environment, but you're using the `msi` installer Windows version @hanchao0606, right?

**Comment by anaisbetts** [comment] 2024-06-21 13:44
Windows doesn't generally have a concept of an app vs. terminal PATH like macOS - there is a system-wide PATH and a user-specific PATH, but those should be identical if being read by the same user

**Comment by Byron** [comment] 2024-06-21 20:25
There now is [another issue with git.exe not being available](https://github.com/gitbutlerapp/gitbutler/issues/4142) despite being installed, so maybe we can put that line of conversation there while focussing on the network-connection issue here.

And while reading the subject of this issue again I thought that maybe this state can be simulated. The frontend should have tools to slow down the network to a crawl, even though I fear this might also affect the communication to localhost. But if that can be excluded, maybe that's an avenue to see what really is causing the delays.

Lastly, I'd think that the backend would simply fail immediately if one were to disable Wifi, and I am not sure how it's possible to simulate a mean firewall that just endlessly delays all connection attempts. Maybe [`Lil Snitch`](https://en.wikipedia.org/wiki/Little_Snitch) would be able to help with that (but a glance on their website didn't show more than blocking connections entirely, which probably is instant).

**Comment by hanchao0606** [comment] 2024-06-23 01:21
Thank you all for your help and suggestions!

**Comment by Byron** [comment] 2024-06-24 07:16
There is [another issue](https://github.com/gitbutlerapp/gitbutler/issues/4142#issuecomment-2185779605) where it turned out that `git.exe` indeed isn't in the PATH, but the msys-git bash is. Once the `PATH` was fixed on system level, `git.exe` could be found.

Maybe this is something you could try.

**Comment by hanchao0606** [comment] 2024-06-25 03:04
@Byron  Thanks you very mach for your replay. I will try.

**Comment by hanchao0606** [comment] 2024-06-25 09:07
@Byron After the slow problem is solved, let me know. very Thanks you.

**Comment by hanchao0606** [comment] 2024-07-05 22:51
Hi
@Byron  @krlvi 
I found that on computers with internet access, deleting the following `C:\Users\Administrator\AppData\Local\com.gitbutler.app\images` file and disconnecting from the internet also slowed down the opening of the app.

**Comment by Byron** [comment] 2024-07-06 07:36
Thanks a lot for researching this! 

I think that this folder contains image assets, and the most numerous of these would be [the profile pictures of commit authors](https://github.com/gitbutlerapp/gitbutler/blob/929eb52224e573c68043ac2c8d7b60684f27f9d0/crates/gitbutler-core/src/assets.rs#L91-L99). If there are many authors in a project, a lot of assets have to be downloaded, and probably that's not tuned as it should be to be non-blocking.

I am very interested in sorting this out, and will put it on my list.

**Comment by ndom91** [comment] 2024-07-09 16:20
> @Caleb-T-Owens do you think we could have this thing performing nicely while doing all in the frontend? Or given this info, maybe it's worth having some kind of proxy-ing system, just in a better shape

I'm a bit confused as to why we fetch the image data via this proxy to begin with. I'd imagine passing the URL (i.e. `github.com/{username}.png`) to the frontend and letting the browser do what it does best would perform better, no? 🤔

**Comment by krlvi** [comment] 2024-07-09 16:59
hmm, that makes sense @ndom91 , but i dont know what to make of Byron's test where he measured the operation being slower...

**Comment by Byron** [comment] 2024-07-10 16:36
The latest nightly *should* behave much better, could you give it a try @hanchao0606 ?

**Comment by hanchao0606** [comment] 2024-07-11 09:50
Thank you very much, I will try it as soon as possible. @Byron

**Comment by hanchao0606** [comment] 2024-07-11 09:54
> The latest nightly _should_ behave much better, could you give it a try @hanchao0606 ?

@Byron Thank you very much, the problem is solved.

**Comment by Byron** [comment] 2024-07-11 10:42
Thanks for trying it out, @hanchao0606 .

Is there anything else that's not working properly or otherwise wonky in your network environment? Even minor things would be good to know, maybe even in a new issue.

However, if the slowness is generally resolved, I think the issue could be closed, what do you think?

**Comment by hanchao0606** [comment] 2024-07-15 01:34
Hi, @Byron 
Thank you for your help and support. The slowness issue has been resolved, so I believe we can close this issue now. For any other minor issues, I will report them on other platforms

**Closed** 2024-07-15 04:58 UTC
Labels: os:windows, performance
