### ISSUE TITLE
📦 FlatPak package

### ISSUE THREAD

**Issue by alexanderadam** [gitbutlerapp/gitbutler#2509] opened 2024-01-11 11:29 UTC
While the [AppImage](https://releases.gitbutler.com/releases/release/0.9.14-525/linux/x86_64/git-butler_0.9.14_amd64.AppImage) is nice, it also feels weird a bit and automatic app updates aren't possible.

Hence I wanted to install GitButler natively but I needed an RPM since I'm running Fedora.
I thought that I could just convert the `.deb` package with [Alien](https://en.wikipedia.org/wiki/Alien_(file_converter)) (`sudo alien -r git-butler_0.9.14_amd64.deb`) but I'm getting this error when trying to install it:

![image](https://github.com/gitbutlerapp/issues/assets/372620/63727d3d-717f-4a61-9c7d-52875344fc07)

So I guess a native installation won't work.

Hence I'd like to see a [Flatpak](https://flatpak.org/) to be available. It works on every Linux distribution the same while also allowing to update the apps centralised.

**Comment by namanlp** [comment] 2024-02-09 21:33
Hi @alexanderadam ,

App updates are there in the appimage, don't worry about that. Whenever the update is available, there should be a pop up in the application ( I saw that just now myself )

I am not sure about flatpack, but RPM bundles will be served with Tauri 2.0-beta. PKGBUILDS support will also be added soon ( most probably, I am working on that ).

So, with Tauri 2.0, we will have native support for *most* generally used distros, that is Arch Based, Fedora based and Debian based distros, and also there is AppImage if you are on any other. So, need of Flatpacks will be more or less eliminated in my humble opnion.

**Comment by namanlp** [comment] 2024-02-09 22:40
Btw, here is how the pop up looks right now for AppImage

![image](https://github.com/gitbutlerapp/gitbutler/assets/66401604/4fbdd328-1f9d-49b0-b7b1-4a49e3f468ac)

**Comment by joezhouchenye** [comment] 2024-03-02 12:34
I found this app in flathub and the flatpak version doesn't work. The appimage version works well.

I got an empty window and the following error if I run it in terminal.

![image](https://github.com/gitbutlerapp/gitbutler/assets/59191277/dd2eacbe-2c6b-465f-8ed4-47351a9f5b7a)
![image](https://github.com/gitbutlerapp/gitbutler/assets/59191277/907fff76-3283-4bb0-bd03-c8352bed794c)

**Comment by ndom91** [comment] 2024-08-22 15:26
I'm going to close this issue as the Flatpak version is a community created bundle. We recommend using the AppImage if you can't use the `.deb` or `.rpm`. Updating from within the AppImage is possible nowadays as well :pray: 

Feel free to open another issue if you have a specific problem with any of the above distributions!

**Closed by ndom91** 2024-08-22 15:26 UTC
Labels: os:linux, distribution, planned

**Comment by ndom91** [comment] 2024-08-23 08:36
Unfortunately Tauri v1 doesn't support Flatpak. We're happy to work with folks in the community if someone wants to maintain it, it's just not something we can do at the moment.

**Comment by ndom91** [comment] 2024-09-03 09:34
So we've actually decided to go with the migration to Tauri v2 this week, meaning we should be able to put out a first-party Flatpak package in the near future :+1:

**Comment by honnip** [comment] 2024-09-19 16:08
The problem is how to handle permissions and sandboxing of the package, not how to build, or who builds it.

I remember that I and a few people on the gitbutler team have write access to the https://github.com/flathub/com.gitbutler.gitbutler. Please contribute there.

Providing flatpak package does not help here. Cannot publish on flathub, no update, permission/sandbox issues still there, etc.




---
@joezhouchenye that's a bug of webkitgtk

**Comment by ndom91** [comment] 2024-11-12 15:53
Hey folks, we finally finished the Tauri v2 update and are working on a first-party flatpak! @honnip I reached out to you a few days ago via discord dm - we're still happy to collaborate here :grin: 

We've love to get some initial feedback of an early build. I believe `push`-ing to HTTPS remotes still isn't working due to it not being able to pop-up the auth dialog.

- Early build (based off of `master` as of 12.11.24): https://drive.google.com/file/d/1N-ZScmvj16jgZF05dHYOJzS84gfV0w6S/view?usp=sharing
- PR: https://github.com/gitbutlerapp/gitbutler/pull/5473
