### ISSUE TITLE
[New Feature] base branches off other branches

### ISSUE THREAD

**Issue by daniilS** [gitbutlerapp/gitbutler#4578] opened 2024-08-01 16:38 UTC
It would be nice to be able to base a virtual branch based on another branch, the way it's possible in git. This should allow changes to exist on the child branch even if they depend/lock onto the parent branch, unapplying the parent branch should also unapply all child branches, and reapplying the parent branch should reapply any child branches that were previously applied (so the data structure of each branch needs to know its parent branch, and whether it wants to be applied or not - and it will only be applied if it wants to be applied _and_ its parent branch is applied).

If it's relevant, here's the specific use case I have in mind:

I have a feature branch `feature`. It contains a new feature that isn't quite ready to be merged into `main` (e.g. not documented yet, doesn't pass all tests, breaks some backwards compatibility, etc). However, it works well enough that users who understand the limitations are already using it, either cloning the branch and installing from source, or using a package manager that can install from a git repository (e.g. pip install).

I apply the branch when I want to use the new feature or work on it, and unapply it when doing other development to make sure it doesn't break anything. At some point, I decide to try out an additional modification on top of the `feature` branch. I don't want to break anything for users of `feature`, so I would like to create a new branch `feature-additionalfeature`, which depends on `feature`, and will eventually either be merged into `feature` or discarded.

**Comment by Byron** [comment] 2024-08-01 17:29
Thanks for the suggestion! Stacked Virtual Branches, I see :).

**Comment by krlvi** [comment] 2024-08-16 12:38
I will close this one as a duplicate of https://github.com/gitbutlerapp/gitbutler/issues/3309 so that we can have all the communication in one place

**Closed by krlvi** 2024-08-16 12:38 UTC
Labels: new feature, planned
