### ISSUE TITLE
Can't be opened after closing on Debian machine.

### ISSUE THREAD

**Issue by thinhha97** [gitbutlerapp/gitbutler#2772] opened 2024-02-17 01:29 UTC

**Comment by iron3oxide** [comment] 2024-02-17 19:33
Probably related to or duplicate of #2630

**Comment by krlvi** [comment] 2024-02-18 16:43
closing as duplicate of https://github.com/gitbutlerapp/gitbutler/issues/2630

**Closed by krlvi** 2024-02-18 16:43 UTC
