### ISSUE TITLE
Arch linux, KDE: Browser not opening, missing menu bar, dark mode not detected, system tray icon invisible

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2808] opened 2024-02-19 12:21 UTC
i don't know if it has been reported yet, but right now on (arch linux, using kde plasma, appimage version 0.10.11 downloaded from the website) everything that tries to open on the browser doesn't work, the app menu bar doesn't show on the global menu instead is a bar on the top of the window, the only options there are close window and close app, i can't click on the label of options to toggle then, i need to click on the checkbox/switch icon, buttons don't modify the cursor appearance to indicate they're clickable, it didn't detect that the system is in dark mode, the icon on the system tray even after switching the app manually to dark mode is still black making it invisible in the dark gray system tray, clicking on it shows the show/hide gitbutler options, but trying to open it won't open and the hide option doesn't do anything and gets stuck there. the loading text is not vertically centered.

https://discord.com/channels/1060193121130000425/1073202153163857920/1208949404183040000

**Comment by theDevelopper** [comment] 2024-02-21 07:36
can confirm. does not work either on 0.10.12
Cannot use the app really and I cannot log in.

**Comment by giopera** [comment] 2024-02-24 07:26
Can confirm, same here with 0.10.16

**Comment by andaag** [comment] 2024-02-26 07:22
Dupe of https://github.com/gitbutlerapp/gitbutler/issues/2765?

**Comment by krlvi** [comment] 2024-08-16 09:42
> Dupe of #2765?

indeed it seems like a duplicate. I will close this issue in favor or #2765 so that we have all the conversation in one place. Thanks for reporting, and feel free to open new issues with things that you discover

**Closed by krlvi** 2024-08-16 09:42 UTC
Labels: bug, os:linux, UI
