### ISSUE TITLE
enh: support ssh auth with ssh-agent

### ISSUE THREAD

**Issue by rbtcollins** [gitbutlerapp/gitbutler#2902] opened 2024-02-24 15:03 UTC
Related to #2901 but this is about how using an existing key works.

I have an existing ssh setup for pushing to github; all that is needed is to run git commands as-is. I'm sure git-butler is using a git library, but that should still be able to support the ssh agent protocol.

Having my passphrase stored in an app with reversible encryption is rather less satisfying than not having it stored at all :) .

**Comment by Byron** [comment] 2024-04-22 13:41
Thanks for reporting!

As of Version 0.11.3 (20240419.070253), there is the option to fetch and push directly through the Git executable, which would inherit all of its capabilities.

<img width="626" alt="Screenshot 2024-04-22 at 15 39 57" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/c8a2b87e-6474-49cb-8d66-5ea98aa87bcf">

Do you think this would be a resolution for the issue described here?

**Comment by Qix-** [comment] 2024-04-30 14:11
Hey there - going to close as a dupe of #3624 (which has been solved). Let me know in that issue if this still doesn't work :)

Thanks for the report!

**Closed by Qix-** 2024-04-30 14:11 UTC
Labels: UX, feedback requested, auth*
