### ISSUE TITLE
Windows - Cannot add any git directory

### ISSUE THREAD

**Issue by Inovvia** [gitbutlerapp/gitbutler#2555] opened 2024-02-06 15:34 UTC
**Steps to reproduce:**

1. Start via pnpm tauri dev
2. Press Add New Project
3. Wait for the prompt
4. Using windows file picker select a folder w/ a valid git repo.

> ipc->add_project: {"path":"C:\\Users\\username\\Documents\\websites\\git"} Error: Something went wrong
    at UserError.fromError (ipc.ts:30:10)
    at ipc.ts:81:33
    at async ProjectService.add (projects.ts:79:19)
    at async HTMLButtonElement.onNewProject (Welcome.svelte:17:23) {code: 'errors.unknown', message: 'Something went wrong'}

I even tried creating a new git repo from scratch in a different directory and disk, but the issue still happened.

![image](https://github.com/gitbutlerapp/gitbutler/assets/70137651/b2856102-d66c-435c-ae26-982447735262)

**Comment by krlvi** [comment] 2024-02-06 20:16
Unfortunately windows support is not there yet, the issue is rooted in libgit2/openssl iirc.
@Qix- do we wanna make an issue here on GitHub to track it?

**Comment by Qix-** [comment] 2024-02-06 21:59
Yeah, so far we've only gotten builds working on Windows, there's a number of issues with actually running it. We're doing some refactoring to move stuff to core crates and have a much better foundation on which we can build the app that will all be Windows-tested. It'll take some time though.

We're looking into ways to use GitButler on windows in the meantime though.

**Comment by Byron** [comment] 2024-04-21 13:42
Since there is an [MSI based installer](https://gitbutler.com) for Windows, I'd think that it is more usable now. Is this specific issue fixed?

**Comment by lennybacon** [comment] 2024-04-21 15:35
You can open a repo now. But a lot of buttons still seem to have no function at all. Not a usable state (yet)…

**Comment by Qix-** [comment] 2024-04-22 09:38
@lennybacon would you mind opening new issues for buttons that aren't working? Going to close this for now as this is probably no longer an issue (please let me know if that's not the case).

**Closed by Qix-** 2024-04-22 09:38 UTC
Labels: os:windows
