### ISSUE TITLE
Package as Flatpak

### ISSUE THREAD

**Issue by vanillajonathan** [gitbutlerapp/gitbutler#2619] opened 2024-02-13 13:17 UTC
Package as [Flatpak](https://flatpak.org/) and publish on [Flathub](https://flathub.org/).

**Comment by namanlp** [comment] 2024-02-14 21:29
Duplicate of https://github.com/gitbutlerapp/gitbutler/issues/2509

Can be closed

**Comment by Byron** [comment] 2024-04-21 12:30
Closed as duplicate.

**Closed by Byron** 2024-04-21 12:30 UTC
