### ISSUE TITLE
[BUG] UI not rendering properly

### ISSUE THREAD

**Issue by mihailnicamn** [gitbutlerapp/gitbutler#2647] opened 2024-02-13 22:01 UTC
<img width="1156" alt="Screenshot 2024-02-13 at 23 57 15" src="https://github.com/gitbutlerapp/gitbutler/assets/110503052/bb067c92-7403-4db8-bcdf-d1d5482be3ad">

Seems like something is broken 😅 
webp not rendering (tried switching 1 webp to png just to check)

styling seems not how it was intented 
(webkit (15613.3.9.1.16, 15613) &/ sveltekit) 

ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2026

**Comment by wirelyre** [comment] 2024-02-14 01:57
Probably a duplicate of #2613.

**Comment by mihailnicamn** [comment] 2024-02-16 21:46
UPDATE: seems like v0.10.10 fixes the css issues, still web does not get rendered
<img width="1296" alt="Screenshot 2024-02-16 at 23 43 56" src="https://github.com/gitbutlerapp/gitbutler/assets/110503052/b8f14da3-0ee7-4cf3-b0c1-510370ff6fad">

**Comment by PavelLaptev** [comment] 2024-04-15 23:29
@mihailnicamn thank you for your report! We've replaced all WebP images with SVG. Should be fixed in the latest releases.
Let's reopen the issue if you still encounter the issue.

**Closed by PavelLaptev** 2024-04-15 23:29 UTC
Labels: bug
