### ISSUE TITLE
Unable to Enter Description When Creating Pull Request

### ISSUE THREAD

**Issue by cuervolu** [gitbutlerapp/gitbutler#5360] opened 2024-10-30 01:31 UTC
### Version

0.13.7

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

Since the latest or previous update, it has become impossible to enter a description when creating a pull request from GitButler. It doesn't allow me to input any text, whether it's for the AI prompt description or the pull request description itself. I've tried troubleshooting, but the issue persists. This is affecting both the AI prompt and the main pull request description fields.

https://github.com/user-attachments/assets/3543a8c7-6274-4d83-8925-b99950fdc2d9

### How to reproduce

To reproduce this issue, follow these steps:

1. Commit some changes.
2. Click on "Create pull request."
3. Attempt to enter text in the modal that appears; you will notice that only the title can be entered, with the description fields remaining uneditable.

### Expected behavior

GitButler should allow me to enter descriptions for both the AI prompt and the pull request itself.

**Comment by Byron** [comment] 2024-10-30 06:45
Thanks for reporting, and sorry for the hassle!

A quick test revealed that at least on MacOS it's working as expected.

<img width="652" alt="Screenshot 2024-10-30 at 07 40 25" src="https://github.com/user-attachments/assets/8e8e6c10-ec72-48b2-ac99-deaaa21460e6">

However, @ndom91 would be able to test the AppImage version and maybe it's an issue just there.

It's notable that I don't have any AI feature enabled, but even when doing so it works as expected.

**Comment by ndom91** [comment] 2024-10-30 09:23
Hey thanks for reaching out. We're aware of this internally and it should be fixed in a day or two. 

The issue is down to (once again 😂) `libwebkit2gtk`. We're planning on shipping a Tauri v2 upgrade today or tomorrow though, which brings with it a new version of that library which I've confirmed fixes this issue. 

You can try out the nightly `0.5.845` to try the latest release of the Tauri v2 branch.

**Comment by ndom91** [comment] 2024-10-30 15:08
@cuervolu we've just published the nightly after merging the Tauri v2 update. Can you give `0.5.849` a shot? ([app.gitbutler.com/downloads](https://app.gitbutler.com/downloads)).

**Comment by cuervolu** [comment] 2024-10-30 15:51
I just tried it, and it works perfectly. Thank you very much for the prompt response and solution.

![image](https://github.com/user-attachments/assets/1a61d364-4704-4fda-84dc-f1bd10891c1c)

**Closed** 2024-10-30 16:12 UTC
Labels: bug, os:linux, UI
