### ISSUE TITLE
Failed to set base branch

### ISSUE THREAD

**Issue by qualmon** [gitbutlerapp/gitbutler#2658] opened 2024-02-14 07:32 UTC
I cannot enter the remote/main branch manually, and none of the ones in the list correspond to my remote. I've renamed origin to something else but it does not show up in the drop down. Going with origin/main give the "failed to set base branch" message.

<img width="1119" alt="SCR-20240214-hxom" src="https://github.com/gitbutlerapp/gitbutler/assets/34239922/0f3fe172-ac29-4f5f-a46f-6c02831a17f7">

**Comment by mtsgrd** [comment] 2024-02-14 14:48
Thanks for reporting this! Does the list in the UI not match the output of `git branch -r`?

**Comment by GrimalDev** [comment] 2024-02-15 16:16
same here! the branch -r is the same...

**Comment by qualmon** [comment] 2024-02-15 19:44
The list matches `git branch -r`.

**Comment by luyao777** [comment] 2024-07-16 07:04
This issue may have been caused by some deferred commits in the code. I also encountered this problem, and it can be resolved by restarting the software after committing all the code.

**Comment by Caleb-T-Owens** [comment] 2024-08-15 13:28
We've iterated on this area of the codebase; could someone please try to reproduce, and provide logs if its still happening.

Many thanks for your patience.

**Comment by krlvi** [comment] 2024-09-10 18:24
Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.

**Closed by krlvi** 2024-09-10 18:24 UTC
Labels: bug, feedback requested

**Comment by Aeramor** [comment] 2024-10-31 01:56
Just ran into this issue. Everything was working fine then I updated to 0.13.8
```
Failed to set base branch
TOML parse error at line 39, column 13 | 39 | ownership = ''' | ^^^ ownership ranges cannot be empty
```

**Comment by Byron** [comment] 2024-10-31 06:18
It's probably best to open a new issue for this or add a comment to [one of the existing issues](https://github.com/gitbutlerapp/gitbutler/issues?q=is%3Aissue+is%3Aopen+%22ownership+ranges+cannot+be+empty%22) that seem to sport this error message.

For me it would be most useful to learn how this issue arose - and judging from the existing issues there are various ways to get there, maybe the one above is new even? Thank you.
