### ISSUE TITLE
Type to search/filter target branch selector

### ISSUE THREAD

**Issue by abjorck** [gitbutlerapp/gitbutler#2590] opened 2024-02-12 07:28 UTC
When opening a git project with hundreds or branches it is tedious to find the right "target" by scrolling

**Comment by inickt** [comment] 2024-05-10 13:02
Was about to open a request for this too– thanks to #2923 basically being done in #3677, unfortunately now I have 837 across the remotes I have set up for one of my repos 😅

**Comment by krlvi** [comment] 2024-06-12 11:35
Hello, thanks to @estib-vega, this should be now fixed. Would you mind trying it out with the latest release (0.12.4)?

**Comment by inickt** [comment] 2024-06-14 17:02
@krlvi This is great! Definitely a nice QOL improvement. Seems to be 1 tiny UI bug where if you select the remote with your mouse, it doesn't update the UI. Functionally it seems to work though.

https://github.com/gitbutlerapp/gitbutler/assets/4574041/0f15ea98-be81-4940-bb53-7468b59ec0f7

Also might be nice if the cursor shows up when typing (or always reset the filter) but that is such a minor nit. It looks if you have previously typed to filter (and select), and then you type again, it will append, but otherwise it will erase the filter completely (what I would expect to happen every time).

**Comment by estib-vega** [comment] 2024-06-17 19:51
Dang, nice catch! I think this should fix that: https://github.com/gitbutlerapp/gitbutler/pull/4102

It will reset always as a default

**Comment by marktoman** [comment] 2024-06-18 04:46
A major bug: If you uncheck something that filters out all branches, it makes the filter button disappear, making it impossible to revert the filter.
![Screenshot 2024-06-18 at 6 42 31](https://github.com/gitbutlerapp/gitbutler/assets/47689923/de01918c-233f-472d-a7e8-58ff5fd275c4)

**Comment by Byron** [comment] 2024-06-18 05:07
Great catch, I can confirm that.

What's worse is that it survives reloads!

https://github.com/gitbutlerapp/gitbutler/assets/63622/583beb0a-a4f7-470d-95cc-e7b58535c6dd

**Comment by estib-vega** [comment] 2024-06-18 05:08
Hey @marktoman 👋
That's a big one indeed, nice catch! But I think that bug is unrelated to this issue.

This other PR should fix that, though: https://github.com/gitbutlerapp/gitbutler/pull/4103

**Comment by Byron** [comment] 2024-06-18 05:10
That's true, putting the feedback label back, as this issue is talking about the target branch selector.

**Comment by Caleb-T-Owens** [comment] 2024-08-15 13:01
<img width="635" alt="Screenshot 2024-08-15 at 15 00 44" src="https://github.com/user-attachments/assets/e401b642-ba1b-441b-8875-bcf8686e4ae0">

The issues mentioned here should all be resolved. Feel free to open individual issues if more issues come up.

**Closed by Caleb-T-Owens** 2024-08-15 13:01 UTC
Labels: enhancement, UX/UI, feedback requested
