### ISSUE TITLE
Under certain conditions clicking a web link in a PR will replace the Gitbutler UI with the links web page

### ISSUE THREAD

**Issue by NigelBreslaw** [gitbutlerapp/gitbutler#4422] opened 2024-07-17 14:14 UTC
### Version

0.12.12

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue
<img width="862" alt="Screenshot 2024-07-17 at 16 09 15" src="https://github.com/user-attachments/assets/b34c1c98-4c33-43dd-bbd2-fad06e9f5e90">
<img width="1030" alt="Screenshot 2024-07-17 at 16 09 33" src="https://github.com/user-attachments/assets/791a03e0-bd88-4be7-92d8-3dcb6ce6aff1">

In the first screenshot you can see remote PR's that have been created by dependabot. Most of the links e.g. 'vitest' will open in your web browser. But if you twirl open the 'changelog' or 'commits' then clicking those links cause Gitbutler (which I guess is some web framework) to open the page so it now has taken over the whole gitbutler app. 
You then seem to need to restart the app to get the UI back.

### How to reproduce

You can clone my repo which monday to friday will have open dependabot PR's https://github.com/NigelBreslaw/guardian-ghost that should show in Gitbutler?

### Expected behavior

Clicking any link in a PR should open the system web browser.

**Comment by Byron** [comment] 2024-07-18 08:17
Thanks a lot for reporting! I did try to reproduce the issue, but no PR shows up for some reason.
Maybe @ndom91 can give it a shot as the issue seems like it can be fixed with just the right setting (or so I hope).

**Comment by NigelBreslaw** [comment] 2024-07-18 08:31
Sorry a repo where the dependabot PRs are still open is https://github.com/NigelBreslaw/unintuitive

**Comment by NigelBreslaw** [comment] 2024-07-19 10:28
This repo would be better to use for reproduction as I can leave the PR open there. https://github.com/NigelBreslaw/unintuitive/

**Comment by mtsgrd** [comment] 2024-07-19 22:03
I think the problem was lack of `target="blank"` config for most markdown rendering. Fixed here: #4445

**Comment by Byron** [comment] 2024-07-20 06:58
Thanks for the fix!

By tomorrow, a [new nightly](https://app.gitbutler.com/downloads) will be available and incorporate the fix. Maybe you get to try it and can validate that it works for you. Thanks again!

**Closed** 2024-08-16 09:47 UTC
Labels: bug, UI, feedback requested

**Comment by ndom91** [comment] 2024-08-16 09:48
I was no longer able to reproduce this. Feel free to open a new issue if you have any more problelms :pray:
