### ISSUE TITLE
Drag'n'drop tp branch should also work with title

### ISSUE THREAD

**Issue by koppor** [gitbutlerapp/gitbutler#4787] opened 2024-08-29 07:40 UTC
### Version

0.12.16

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

Changes can be dropped to virtual branches. As drop target, only the file list is possible. But the header should also be a drop target. The change should be added to changed files, too.

### How to reproduce

![image](https://github.com/user-attachments/assets/96b3fa49-b9f2-47bd-b0fb-ea4e9d9d8b34)

### Expected behavior

Change should be added to changed files.

**Comment by Byron** [comment] 2024-08-29 11:31
Hi @PavelLaptev , I thought his one might be interesting for you.

Personally I tried it and found it understandable not to be able to drop files off outside the box, and to me it would be unexpected to accept a drop on the title which I'd use to last-minute cancel the drop.

**Comment by koppor** [comment] 2024-08-29 22:47
Thank you for the answer. I need to read where I drop and I target that text. Similar to darts, where the target areas are marked and I need to hit them. Different to bins where the bin is labeled with the contents, but I need to hit the bin, not the label.

**Comment by PavelLaptev** [comment] 2024-09-01 18:52
I believe the top of the lane should not have a drop area, or at least it shouldn't be visible.
Each lane can have multiple drop zones for files, and it's important to clearly distinguish them because they trigger different actions.
When you have a PR the lane header will be separated from the "changed files" section with a "PR" card, so in this case there will be two drop zones that duplicate the same action, which could lead to confusion → header to drop files then not droppable PR card then the droppable "changed files" section again (see image below). Also, drop zones have this overlay color when they're active, I would like to leave the lane header clean and visible without a drop capability. 

<img width="1374" alt="image" src="https://github.com/user-attachments/assets/fd3903b7-b5a2-4666-9eb2-c089b1afcecc">

**Comment by estib-vega** [comment] 2024-10-16 17:54
Closing this. Not allowing the drag and drop to be the header is by design

**Closed by estib-vega** 2024-10-16 17:54 UTC
Labels: UX
