### ISSUE TITLE
File is locked in two virtual branches for the same changes

### ISSUE THREAD

**Issue by endercrest** [gitbutlerapp/gitbutler#2882] opened 2024-02-22 20:08 UTC
Observing some odd behaviour around the file locking mechanism. In the picture below, the `typeConversions.ts` file has incorrectly been locked into two branches simultaneously. It seems GitButler has gotten confused and has "reverted" the initial changes and locked that to the non-default branch and then re-applied those changes to the default branch and locked it

Background: `typeConversions.ts` was previously changed in the non-default branch. And there are no associated changes in the default branch.

![image](https://github.com/gitbutlerapp/gitbutler/assets/2616075/140220c3-c539-4f81-8acc-a1d81a76f1eb)

**Comment by daniilS** [comment] 2024-04-16 12:39
@endercrest #3136 which I suspect had the same root cause was fixed in the latest nightly (0.5.408), so this might be too.

**Comment by krlvi** [comment] 2024-08-16 11:50
Hey @endercrest - thanks for reporting this. A few months back we had quite a number of these kinds of issue, with many people on Discord pinging us about it. 
I think we have squashed most of the bugs in this area now. Are you still experiencing this type of issue in the more recent versions of the app?

**Comment by krlvi** [comment] 2024-09-10 18:29
Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.

**Closed by krlvi** 2024-09-10 18:29 UTC
Labels: bug, feedback requested
