### ISSUE TITLE
Windows update installer not signed

### ISSUE THREAD

**Issue by cheng-liven** [gitbutlerapp/gitbutler#5752] opened 2024-12-06 00:53 UTC
### Version

0.14.2

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

Windows update installer shown unknown author

<img width="340" alt="Screenshot 2024-10-18 105340" src="https://github.com/user-attachments/assets/c2302aad-b742-407f-a8ad-dabb9429099d">

### How to reproduce

In app update on Windows

### Expected behavior

`Publisher: GitButler Inc.` ?

Cost:
probably the cheapest one? Azure service: ($10/m)
https://learn.microsoft.com/en-us/azure/trusted-signing/
https://github.com/marketplace/actions/trusted-signing

Traditional certificates: several hundreds of $ per year

**Comment by Byron** [comment] 2024-12-06 07:48
Thanks a lot for reporting!

I think this is an artefact of a real-world windows machine not currently being available. Future releases will be signed once again.

CC @ndom91 .

**Comment by ndom91** [comment] 2024-12-06 09:06
It looks like that's an older version, 0.13.2, can you try with the 0.14.2 msi? 

We do have a windows box in the office that signs all of the windows releases so that's very strange to see

**Comment by chicheng** [comment] 2024-12-08 12:19
![image](https://github.com/user-attachments/assets/b252d38e-9397-4227-99f6-20883cb3345f)

It's always unknown publisher since 0.10.x on both of my Windows 11 OS.

**Comment by Byron** [comment] 2024-12-08 19:05
Thanks for sharing!

This seems to be something else then, as the MSI files I can download from the website are definitely signed as per Win11 on ARM.

https://github.com/user-attachments/assets/78dc91b7-df2d-48e8-a5da-8038ca2efc2b

It's strange, I wonder how this can happen.

**Comment by ndom91** [comment] 2024-12-08 20:35
@chicheng can you tell from which URL it is downloading the update from? i.e. what file is it grabbing exactly? Something like `mitmproxy` might do the trick

**Comment by cheng-liven** [comment] 2024-12-09 00:39
> @chicheng can you tell from which URL it is downloading the update from? i.e. what file is it grabbing exactly? Something like `mitmproxy` might do the trick

It's the auto update downloaded by GitButler update prompt 

<img width="193" alt="image" src="https://github.com/user-attachments/assets/ddb4cbbf-de76-4eda-ae62-bb14517bcb6e">

**Comment by Byron** [comment] 2024-12-09 06:43
That was the hint I needed! And it's something that easily reproduces.

<img width="1136" alt="Screenshot 2024-12-09 at 07 43 11" src="https://github.com/user-attachments/assets/9ebcfd69-ea0b-417c-94b1-b05b7797274f">


It seems the downloaded file is lacking the signatures somehow.

**Comment by ndom91** [comment] 2024-12-09 11:16
> That was the hint I needed! And it's something that easily reproduces.
> 
> <img width="1136" alt="Screenshot 2024-12-09 at 07 43 11" src="https://github.com/user-attachments/assets/9ebcfd69-ea0b-417c-94b1-b05b7797274f">
> 
> 
> It seems the downloaded file is lacking the signatures somehow.

Nice thanks for confirming. Yeah I saw only some of the entries in the `release_builds` table have signatures, I'll take a look at how we're pointing at the wrong one

**Comment by ndom91** [comment] 2024-12-12 10:56
I'm testinga a PR currently which also zips up the signed msi and uploads it (replacing the pre-existing unsigned `*.msi.zip`) in the s3 bucket directory: https://github.com/gitbutlerapp/gitbutler/pull/5820.

Let's see how the windows output looks here: https://github.com/gitbutlerapp/gitbutler/actions/runs/12294686564

**Comment by schacon** [comment] 2024-12-17 12:42
#5820 was just merged, which I believe fixes this issue. @cheng-liven please let me know if this happens again - the next mainline build should be signed properly.

**Closed by schacon** 2024-12-17 12:42 UTC
Labels: bug, os:windows, distribution
