### ISSUE TITLE
After opening the project, move here is always displayed and cannot be closed.

### ISSUE THREAD

**Issue by hr1ycfl** [gitbutlerapp/gitbutler#4231] opened 2024-07-03 02:08 UTC
### Version

0.12.7

### Operating System

Mac OS X

### Distribution Method

dmg (Intel)

### Describe the issue

After opening the project, move here is always displayed and cannot be closed.

<img width="1797" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/22468684/b716f8db-a899-4606-a718-c93a784ee23b">

<img width="1252" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/22468684/7dd29b0c-a172-4ed1-b6ad-fe3f79e8d150">

**Comment by krlvi** [comment] 2024-07-03 13:30
Hey! Thank you for reporting this. This appears to be the same as this issue over here: https://github.com/gitbutlerapp/gitbutler/issues/4209

It seems like a regression that we introduced in the last release, I am sorry about that. One person in the other issue mentioned that the latest nightly build resolves the problem - I can't immediately verify that but if you feel like trying it out, you can grab a build from over here: https://app.gitbutler.com/downloads

Because this is a duplicate of #4209 I will close this one if you don't mind. If you run into any separate problems, github issues are very much appreciated, thank you!

**Closed by krlvi** 2024-07-03 13:30 UTC
Labels: bug
