### ISSUE TITLE
Can't back out of adding new project

### ISSUE THREAD

**Issue by mkroening** [gitbutlerapp/gitbutler#2539] opened 2024-02-05 12:57 UTC
On macOS, after clicking “Add new project” and selecting a directory, you are prompted to select a target branch. There is a “Back” button next to “Let's go!”, but it does not work. Even after restarting the app, I can't leave the screen.

Resetting the app with `rm -rf ~/Library/Application\ Support/com.gitbutler.app` works.

**Comment by OlegGulevskyy** [comment] 2024-02-12 21:03
I can't reproduce it on my side, is it still an issue?

**Comment by Kamaropoulos** [comment] 2024-02-14 10:05
Yeah, I'm also having the same issue.

**Comment by mkroening** [comment] 2024-02-14 14:04
> I can't reproduce it on my side, is it still an issue?

Sorry for not responding. Yeah, this is still an issue. How can I help you reproduce this?

**Comment by OlegGulevskyy** [comment] 2024-02-14 14:28
I am not really sure, I was just shopping around for ways to contribute to GB and tried to reproduce it without any luck.
I will try again later but if anything comes to mind, please don't hesitate. Maybe someone from GB team will have some thoughts and pointers as well?

**Comment by alexcameron89** [comment] 2024-02-17 15:52
I've had a similar issue. One thing I've noticed is that even if I close the app, and open it back up, the app stays on the ProjectSetup page.
<img width="1312" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/5634381/27b01ea6-6c7c-48af-b5df-70041df30922">

 I'm not familiar with the source code, but I wonder if it's because:
 1. "/" seems to be determined as the ProjectSetup page after attempting to set up a project
 2. Without history, the back button directs to "/" ([source](https://github.com/gitbutlerapp/gitbutler/blob/3a4fb738c89eb4841905a55dee22a3103b873946/gitbutler-ui/src/lib/components/BackButton.svelte#L13))

**Comment by Byron** [comment] 2024-04-21 13:50
I noticed the same, the issue is still present as of Version 0.11.3 (20240419.070253) .

A workaround I employ is to hit "Let's go!", then try the Authentication with the "Auto" option. Since this usually takes longer than I am willing to wait, I go "Back" all the way until the UI drops into the worktree view of the newly added repository.

**Comment by davidbuzz** [comment] 2024-07-13 00:12
I have an identical bug on latest .deb build on ubuntu... I got to the 'project setup' page after selecting a valid, but undesirable git repo to use, and tried to clik 'Back' and the back button doesn't work.  closing and re-opening the app now brings me to the same screen with the same back button still not working.   I dont want to preess continue, as its the 'wrong repo'.

**Comment by Comnir** [comment] 2024-08-10 09:15
From what I understand, when clicking  “Add new project”, the new project is already created in the projects list. So when the root page is opened, by either "Back" or reopening GitButler, it will redirect to project.

So maybe a solution would be to delete the partially-added project when clicking "Back" (recently changed to "Cancel")?

**Comment by Comnir** [comment] 2024-08-10 17:11
I don't have much experience with frontend/JS development, but I made an attempt to implement the suggestion - #4671

**Closed** 2024-08-21 13:36 UTC
Labels: bug, UX, 🎉reproduced🎉
