### ISSUE TITLE
No ssh-agent based authentication on Windows

### ISSUE THREAD

**Issue by gwkunze** [gitbutlerapp/gitbutler#3624] opened 2024-04-29 09:31 UTC
Slightly related to #2902 but specifically for windows. The feature dicussed in that issue is explicitly disabled in Windows (https://github.com/gitbutlerapp/gitbutler/commit/7d01a537d49e0219773dacb1655f6a7a58f5f355) probably for a good reason.

I have the `OpenSSH Authentication Agent` service running in Windows (10) and have my key added and the GIT_SSH environment variable set however I have to type in my passphrase (twice) on any push from GitButler. Note that using `git` from the command line works fine.

**Comment by Qix-** [comment] 2024-04-30 09:54
Hey, thanks for reporting. Looks like `GIT_SSH_COMMAND`, which is what the fork/exec implementation uses, takes precedence over `GIT_SSH` (TIL).

I'll push a fix for this now as we don't even consider `GIT_SSH` at the moment (but can trivially do so).

As a workaround, if you set `GIT_SSH_COMMAND` to whatever is currently in `%GIT_SSH%` it should Just Work.

**Comment by Qix-** [comment] 2024-04-30 10:10
https://github.com/gitbutlerapp/gitbutler/pull/3637 should fix this :)

**Comment by Qix-** [comment] 2024-04-30 10:38
Once [this nightly actions run](https://github.com/gitbutlerapp/gitbutler/actions/runs/8893291905) finishes, a new nightly will be published (there will most likely be a few errors in the last phase, it's a known issue - the nightly will still be published).

When that's the case, can you try the new [Nightly Build](https://app.gitbutler.com/downloads) and see if it fixes your problem?

**Comment by gwkunze** [comment] 2024-04-30 11:40
Hi, I just tried it and ran into a problem, although it might be slightly spoiled by me having another issue (with regular GitButler, not nightly): It wouldn't fetch any more and after a while show an error that it was waiting for input on stdin for my passphrase, so for some reason it stopped popping up a little window asking for my passphrase. I think that is the reason for the first error that showed up:
![image](https://github.com/gitbutlerapp/gitbutler/assets/196545/aba3a3bc-db86-4f5f-aa6d-b0b8d2a159e9)
but that didn't seem to prevent the application from working...

Anyways, that issue is likely unrelated to this one as I was able to fix the other one, the error is:
![image](https://github.com/gitbutlerapp/gitbutler/assets/196545/656f16af-ec05-42d6-aa64-d6b4533fa5c8)
It seems the value goes through string parsing twice as it shows correct first, but without `\` in the second part of the error. I tried changing my Path to include double `\\` and when I do that it successfully pushed to my remote but I'm pretty sure that shouldn't be necessary as none of my other environment variables have their backslashes escaped.

**Comment by Qix-** [comment] 2024-04-30 12:10
Thanks a _lot_ for the feedback. If I had to guess, the first issue might be due to the pipe breaking though I'm not doing any stream parsing for the Git stuff, so I'm not sure what that might be. Is it consistent that you get that error message? If so, do any logs show up in the developer console (View -> Developer Tools) or the application logs (`%APPDATA%\com.gitbutler.app.nightly` I believe)?

As for the second issue, that's super strange! I don't do any parsing there so that's especially bizarre. Let me investigate a bit on my end and see if I can't track down the problem - should be trivially reproducible.

**Comment by Qix-** [comment] 2024-04-30 12:58
Was able to reproduce, turns out it was twofold - both environment variables and arguments have legacy handling on Windows that you have to account for, which is kind of a pain. I *think* #3638 should handle it correctly.

**Comment by gwkunze** [comment] 2024-04-30 13:18
Hmm, the error stopped happening after I restarted GitButler and doesn't seem to reproducible anymore. I'll keep an eye on it to see if it ever happens again.

**Comment by gwkunze** [comment] 2024-04-30 13:19
(the other error, not the environment variable one)

**Comment by Qix-** [comment] 2024-04-30 13:36
Interesting, alright. Might have been unrelated. Can you try the latest nightly to see if it solves the backslash issue?

**Comment by gwkunze** [comment] 2024-04-30 13:58
👍 looks to be working

**Comment by Qix-** [comment] 2024-04-30 14:00
Awesome! Thanks again for the report :)

Will close, let me know if something else is awry and I can fix it ASAP. Cheers!

**Closed by Qix-** 2024-04-30 14:00 UTC
Labels: bug, os:windows, feedback requested, auth*
